# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from ironclad_python.models.activity_author_model import ActivityAuthorModel
from ironclad_python.models.inbound_attachment_model import InboundAttachmentModel
from typing import Optional, Set
from typing_extensions import Self

class InboundEmailResponse(BaseModel):
    """
    InboundEmailResponse
    """ # noqa: E501
    id: Optional[StrictStr] = None
    email_thread_id: Optional[StrictStr] = Field(default=None, alias="emailThreadId")
    type: Optional[StrictStr] = None
    author: Optional[ActivityAuthorModel] = None
    timestamp: Optional[StrictStr] = None
    subject: Optional[StrictStr] = None
    body: Optional[StrictStr] = None
    attachments: Optional[List[InboundAttachmentModel]] = None
    __properties: ClassVar[List[str]] = ["id", "emailThreadId", "type", "author", "timestamp", "subject", "body", "attachments"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['inboundEmail']):
            raise ValueError("must be one of enum values ('inboundEmail')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InboundEmailResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of author
        if self.author:
            _dict['author'] = self.author.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item_attachments in self.attachments:
                if _item_attachments:
                    _items.append(_item_attachments.to_dict())
            _dict['attachments'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InboundEmailResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "emailThreadId": obj.get("emailThreadId"),
            "type": obj.get("type"),
            "author": ActivityAuthorModel.from_dict(obj["author"]) if obj.get("author") is not None else None,
            "timestamp": obj.get("timestamp"),
            "subject": obj.get("subject"),
            "body": obj.get("body"),
            "attachments": [InboundAttachmentModel.from_dict(_item) for _item in obj["attachments"]] if obj.get("attachments") is not None else None
        })
        return _obj


