# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.list_all_workflow_approvals200_response_approval_groups_inner import ListAllWorkflowApprovals200ResponseApprovalGroupsInner
from openapi_client.models.list_all_workflow_approvals200_response_roles_inner import ListAllWorkflowApprovals200ResponseRolesInner
from typing import Optional, Set
from typing_extensions import Self

class ListAllWorkflowApprovals200Response(BaseModel):
    """
    ListAllWorkflowApprovals200Response
    """ # noqa: E501
    workflow_id: Optional[StrictStr] = Field(default=None, alias="workflowId")
    title: Optional[StrictStr] = None
    approval_groups: Optional[List[ListAllWorkflowApprovals200ResponseApprovalGroupsInner]] = Field(default=None, alias="approvalGroups")
    roles: Optional[List[ListAllWorkflowApprovals200ResponseRolesInner]] = None
    __properties: ClassVar[List[str]] = ["workflowId", "title", "approvalGroups", "roles"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListAllWorkflowApprovals200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in approval_groups (list)
        _items = []
        if self.approval_groups:
            for _item_approval_groups in self.approval_groups:
                if _item_approval_groups:
                    _items.append(_item_approval_groups.to_dict())
            _dict['approvalGroups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in roles (list)
        _items = []
        if self.roles:
            for _item_roles in self.roles:
                if _item_roles:
                    _items.append(_item_roles.to_dict())
            _dict['roles'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListAllWorkflowApprovals200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workflowId": obj.get("workflowId"),
            "title": obj.get("title"),
            "approvalGroups": [ListAllWorkflowApprovals200ResponseApprovalGroupsInner.from_dict(_item) for _item in obj["approvalGroups"]] if obj.get("approvalGroups") is not None else None,
            "roles": [ListAllWorkflowApprovals200ResponseRolesInner.from_dict(_item) for _item in obj["roles"]] if obj.get("roles") is not None else None
        })
        return _obj


