# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from ironclad_python.models.record_model_properties_agreement_date import RecordModelPropertiesAgreementDate
from ironclad_python.models.record_model_properties_counterparty_email import RecordModelPropertiesCounterpartyEmail
from ironclad_python.models.record_model_properties_counterparty_name import RecordModelPropertiesCounterpartyName
from ironclad_python.models.record_model_properties_hourly_rate import RecordModelPropertiesHourlyRate
from typing import Optional, Set
from typing_extensions import Self

class RecordModelProperties(BaseModel):
    """
    RecordModelProperties
    """ # noqa: E501
    agreement_date: Optional[RecordModelPropertiesAgreementDate] = Field(default=None, alias="agreementDate")
    counterparty_name: Optional[RecordModelPropertiesCounterpartyName] = Field(default=None, alias="counterpartyName")
    counterparty_email: Optional[RecordModelPropertiesCounterpartyEmail] = Field(default=None, alias="counterpartyEmail")
    hourly_rate: Optional[RecordModelPropertiesHourlyRate] = Field(default=None, alias="hourlyRate")
    __properties: ClassVar[List[str]] = ["agreementDate", "counterpartyName", "counterpartyEmail", "hourlyRate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecordModelProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of agreement_date
        if self.agreement_date:
            _dict['agreementDate'] = self.agreement_date.to_dict()
        # override the default output from pydantic by calling `to_dict()` of counterparty_name
        if self.counterparty_name:
            _dict['counterpartyName'] = self.counterparty_name.to_dict()
        # override the default output from pydantic by calling `to_dict()` of counterparty_email
        if self.counterparty_email:
            _dict['counterpartyEmail'] = self.counterparty_email.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hourly_rate
        if self.hourly_rate:
            _dict['hourlyRate'] = self.hourly_rate.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecordModelProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agreementDate": RecordModelPropertiesAgreementDate.from_dict(obj["agreementDate"]) if obj.get("agreementDate") is not None else None,
            "counterpartyName": RecordModelPropertiesCounterpartyName.from_dict(obj["counterpartyName"]) if obj.get("counterpartyName") is not None else None,
            "counterpartyEmail": RecordModelPropertiesCounterpartyEmail.from_dict(obj["counterpartyEmail"]) if obj.get("counterpartyEmail") is not None else None,
            "hourlyRate": RecordModelPropertiesHourlyRate.from_dict(obj["hourlyRate"]) if obj.get("hourlyRate") is not None else None
        })
        return _obj


