# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from ironclad_python.models.update_workflow_metadata200_response_schema_counterparty_name import UpdateWorkflowMetadata200ResponseSchemaCounterpartyName
from typing import Optional, Set
from typing_extensions import Self

class UpdateWorkflowMetadata200ResponseSchemaLineItemsElementTypeSchema(BaseModel):
    """
    UpdateWorkflowMetadata200ResponseSchemaLineItemsElementTypeSchema
    """ # noqa: E501
    child_attribute: Optional[UpdateWorkflowMetadata200ResponseSchemaCounterpartyName] = Field(default=None, alias="childAttribute")
    another_child_attribute: Optional[UpdateWorkflowMetadata200ResponseSchemaCounterpartyName] = Field(default=None, alias="anotherChildAttribute")
    __properties: ClassVar[List[str]] = ["childAttribute", "anotherChildAttribute"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateWorkflowMetadata200ResponseSchemaLineItemsElementTypeSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of child_attribute
        if self.child_attribute:
            _dict['childAttribute'] = self.child_attribute.to_dict()
        # override the default output from pydantic by calling `to_dict()` of another_child_attribute
        if self.another_child_attribute:
            _dict['anotherChildAttribute'] = self.another_child_attribute.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateWorkflowMetadata200ResponseSchemaLineItemsElementTypeSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "childAttribute": UpdateWorkflowMetadata200ResponseSchemaCounterpartyName.from_dict(obj["childAttribute"]) if obj.get("childAttribute") is not None else None,
            "anotherChildAttribute": UpdateWorkflowMetadata200ResponseSchemaCounterpartyName.from_dict(obj["anotherChildAttribute"]) if obj.get("anotherChildAttribute") is not None else None
        })
        return _obj


