# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class WebhookEventTypeValue(str, Enum):
    """
    WebhookEventTypeValue
    """

    """
    allowed enum values
    """
    STAR = '*'
    WORKFLOW_LAUNCHED = 'workflow_launched'
    WORKFLOW_UPDATED = 'workflow_updated'
    WORKFLOW_CANCELLED = 'workflow_cancelled'
    WORKFLOW_COMPLETED = 'workflow_completed'
    WORKFLOW_APPROVAL_STATUS_CHANGED = 'workflow_approval_status_changed'
    WORKFLOW_ATTRIBUTE_UPDATED = 'workflow_attribute_updated'
    WORKFLOW_COMMENT_ADDED = 'workflow_comment_added'
    WORKFLOW_COMMENT_REMOVED = 'workflow_comment_removed'
    WORKFLOW_COMMENT_UPDATED = 'workflow_comment_updated'
    WORKFLOW_COMMENT_REACTION_ADDED = 'workflow_comment_reaction_added'
    WORKFLOW_COMMENT_REACTION_REMOVED = 'workflow_comment_reaction_removed'
    WORKFLOW_COUNTERPARTY_INVITE_SENT = 'workflow_counterparty_invite_sent'
    WORKFLOW_COUNTERPARTY_INVITE_REVOKED = 'workflow_counterparty_invite_revoked'
    WORKFLOW_DOCUMENTS_ADDED = 'workflow_documents_added'
    WORKFLOW_DOCUMENTS_REMOVED = 'workflow_documents_removed'
    WORKFLOW_DOCUMENTS_UPDATED = 'workflow_documents_updated'
    WORKFLOW_DOCUMENTS_RENAMED = 'workflow_documents_renamed'
    WORKFLOW_DOCUMENT_EDITED = 'workflow_document_edited'
    WORKFLOW_CHANGED_TURN = 'workflow_changed_turn'
    WORKFLOW_PAUSED = 'workflow_paused'
    WORKFLOW_RESUMED = 'workflow_resumed'
    WORKFLOW_SIGNATURE_PACKET_SENT = 'workflow_signature_packet_sent'
    WORKFLOW_SIGNATURE_PACKET_UPLOADED = 'workflow_signature_packet_uploaded'
    WORKFLOW_SIGNATURE_PACKET_CANCELLED = 'workflow_signature_packet_cancelled'
    WORKFLOW_SIGNER_ADDED = 'workflow_signer_added'
    WORKFLOW_SIGNER_REMOVED = 'workflow_signer_removed'
    WORKFLOW_SIGNER_REASSIGNED = 'workflow_signer_reassigned'
    WORKFLOW_STEP_UPDATED = 'workflow_step_updated'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WebhookEventTypeValue from a JSON string"""
        return cls(json.loads(json_str))


