# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.workflow_response_model_attributes_draft_inner_last_modified import WorkflowResponseModelAttributesDraftInnerLastModified
from typing import Optional, Set
from typing_extensions import Self

class WorkflowResponseModelAttributesDraftInner(BaseModel):
    """
    WorkflowResponseModelAttributesDraftInner
    """ # noqa: E501
    version: Optional[StrictStr] = None
    version_number: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="versionNumber")
    filename: Optional[StrictStr] = None
    download: Optional[StrictStr] = None
    last_modified: Optional[WorkflowResponseModelAttributesDraftInnerLastModified] = Field(default=None, alias="lastModified")
    __properties: ClassVar[List[str]] = ["version", "versionNumber", "filename", "download", "lastModified"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowResponseModelAttributesDraftInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of last_modified
        if self.last_modified:
            _dict['lastModified'] = self.last_modified.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowResponseModelAttributesDraftInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "versionNumber": obj.get("versionNumber"),
            "filename": obj.get("filename"),
            "download": obj.get("download"),
            "lastModified": WorkflowResponseModelAttributesDraftInnerLastModified.from_dict(obj["lastModified"]) if obj.get("lastModified") is not None else None
        })
        return _obj


