# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.workflow_last_modified_author_model_one_of import WorkflowLastModifiedAuthorModelOneOf

class TestWorkflowLastModifiedAuthorModelOneOf(unittest.TestCase):
    """WorkflowLastModifiedAuthorModelOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowLastModifiedAuthorModelOneOf:
        """Test WorkflowLastModifiedAuthorModelOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowLastModifiedAuthorModelOneOf`
        """
        model = WorkflowLastModifiedAuthorModelOneOf()
        if include_optional:
            return WorkflowLastModifiedAuthorModelOneOf(
                type = 'counterparty',
                display_name = 'Boba Fett'
            )
        else:
            return WorkflowLastModifiedAuthorModelOneOf(
                type = 'counterparty',
                display_name = 'Boba Fett',
        )
        """

    def testWorkflowLastModifiedAuthorModelOneOf(self):
        """Test WorkflowLastModifiedAuthorModelOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
