# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.base_activity_feed_item_model import BaseActivityFeedItemModel

class TestBaseActivityFeedItemModel(unittest.TestCase):
    """BaseActivityFeedItemModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseActivityFeedItemModel:
        """Test BaseActivityFeedItemModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseActivityFeedItemModel`
        """
        model = BaseActivityFeedItemModel()
        if include_optional:
            return BaseActivityFeedItemModel(
                id = '',
                type = 'comment',
                metadata = openapi_client.models.activity_metadata_model.ActivityMetadataModel(),
                author = openapi_client.models.activity_author_model.ActivityAuthorModel(),
                is_external = True,
                reactions = openapi_client.models.activity_reaction_model.ActivityReactionModel(
                    emoji_id = 'smile', 
                    reactors = [
                        openapi_client.models.user_model.UserModel(
                            id = '', 
                            display_name = '', )
                        ], )
            )
        else:
            return BaseActivityFeedItemModel(
                id = '',
                type = 'comment',
                metadata = openapi_client.models.activity_metadata_model.ActivityMetadataModel(),
                author = openapi_client.models.activity_author_model.ActivityAuthorModel(),
        )
        """

    def testBaseActivityFeedItemModel(self):
        """Test BaseActivityFeedItemModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
