# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.workflow_response_model import WorkflowResponseModel

class TestWorkflowResponseModel(unittest.TestCase):
    """WorkflowResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowResponseModel:
        """Test WorkflowResponseModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowResponseModel`
        """
        model = WorkflowResponseModel()
        if include_optional:
            return WorkflowResponseModel(
                id = '6013609108b8f070cee94fc1',
                ironclad_id = 'IC-1',
                title = 'Consulting Agreement with Jane Doe',
                template = '600b296c3e15a234ab88f884',
                step = 'Review',
                var_schema = openapi_client.models.update_workflow_metadata_200_response_schema.update_workflow_metadata_200_response_schema(
                    counterparty_name = openapi_client.models.update_workflow_metadata_200_response_schema_counterparty_name.update_workflow_metadata_200_response_schema_counterpartyName(
                        type = 'string', 
                        display_name = 'Example String Attribute', ), 
                    amount = openapi_client.models.update_workflow_metadata_200_response_schema_amount.update_workflow_metadata_200_response_schema_amount(
                        type = 'number', 
                        display_name = 'Example Number Attribute', ), 
                    fee = openapi_client.models.update_workflow_metadata_200_response_schema_fee.update_workflow_metadata_200_response_schema_fee(
                        type = 'monetaryAmount', 
                        display_name = 'Example Monetary Amount Attribute', ), 
                    draft = openapi_client.models.update_workflow_metadata_200_response_schema_draft.update_workflow_metadata_200_response_schema_draft(
                        type = 'array', 
                        element_type = openapi_client.models.update_workflow_metadata_200_response_schema_draft_element_type.update_workflow_metadata_200_response_schema_draft_elementType(
                            type = 'document', 
                            display_name = 'Example Document Attribute', ), ), 
                    line_items = openapi_client.models.update_workflow_metadata_200_response_schema_line_items.update_workflow_metadata_200_response_schema_lineItems(
                        type = 'array', ), ),
                attributes = openapi_client.models.workflow_response_model_attributes.WorkflowResponseModel_attributes(
                    counterparty_name = 'Boba Fett', 
                    amount = 123, 
                    fee = openapi_client.models.update_workflow_metadata_200_response_attributes_fee.update_workflow_metadata_200_response_attributes_fee(
                        currency = 'USD', 
                        amount = 50000, ), 
                    draft = [
                        openapi_client.models.workflow_response_model_attributes_draft_inner.WorkflowResponseModel_attributes_draft_inner(
                            version = 'B1QePArXb', 
                            version_number = 2, 
                            filename = 'file.pdf', 
                            download = '/public/api/v1/workflows/594356b9fbcd7f74006fdf8a/document/rJklwCHQ/download', 
                            last_modified = openapi_client.models.workflow_response_model_attributes_draft_inner_last_modified.WorkflowResponseModel_attributes_draft_inner_lastModified(
                                timestamp = '2016-11-17T00:37:22.318Z', 
                                author = openapi_client.models.author.author(), ), )
                        ], ),
                is_cancelled = False,
                is_complete = False,
                status = 'active',
                creator = openapi_client.models.workflow_response_model_creator.WorkflowResponseModel_creator(
                    id = '63d415e0dd0d828c3a878548', 
                    display_name = 'Boba Fett', 
                    email = 'fett@intergalactic.com', 
                    title = 'Director', 
                    username = 'fett@intergalactic.com', 
                    metadata = {}, ),
                created = '2016-11-17T00:37:22.318Z',
                last_updated = '2016-11-17T00:37:22.318Z',
                roles = [
                    openapi_client.models.workflow_response_model_roles_inner.WorkflowResponseModel_roles_inner(
                        id = 'legal', 
                        display_name = 'Legal', 
                        assignees = [
                            openapi_client.models.workflow_response_model_roles_inner_assignees_inner.WorkflowResponseModel_roles_inner_assignees_inner(
                                user_name = 'Boba Fett', 
                                user_id = '63d415e0dd0d828c3a878548', 
                                email = 'bobafett@gmail.com', )
                            ], )
                    ],
                approvals = openapi_client.models.workflow_state_model.WorkflowStateModel(),
                signatures = openapi_client.models.workflow_state_model.WorkflowStateModel(),
                record_ids = [
                    '715f1e37-292f-4e6c-8b48-c07e1b68bccd'
                    ],
                is_revertible_to_review = False
            )
        else:
            return WorkflowResponseModel(
                id = '6013609108b8f070cee94fc1',
                title = 'Consulting Agreement with Jane Doe',
                template = '600b296c3e15a234ab88f884',
                step = 'Review',
                var_schema = openapi_client.models.update_workflow_metadata_200_response_schema.update_workflow_metadata_200_response_schema(
                    counterparty_name = openapi_client.models.update_workflow_metadata_200_response_schema_counterparty_name.update_workflow_metadata_200_response_schema_counterpartyName(
                        type = 'string', 
                        display_name = 'Example String Attribute', ), 
                    amount = openapi_client.models.update_workflow_metadata_200_response_schema_amount.update_workflow_metadata_200_response_schema_amount(
                        type = 'number', 
                        display_name = 'Example Number Attribute', ), 
                    fee = openapi_client.models.update_workflow_metadata_200_response_schema_fee.update_workflow_metadata_200_response_schema_fee(
                        type = 'monetaryAmount', 
                        display_name = 'Example Monetary Amount Attribute', ), 
                    draft = openapi_client.models.update_workflow_metadata_200_response_schema_draft.update_workflow_metadata_200_response_schema_draft(
                        type = 'array', 
                        element_type = openapi_client.models.update_workflow_metadata_200_response_schema_draft_element_type.update_workflow_metadata_200_response_schema_draft_elementType(
                            type = 'document', 
                            display_name = 'Example Document Attribute', ), ), 
                    line_items = openapi_client.models.update_workflow_metadata_200_response_schema_line_items.update_workflow_metadata_200_response_schema_lineItems(
                        type = 'array', ), ),
                attributes = openapi_client.models.workflow_response_model_attributes.WorkflowResponseModel_attributes(
                    counterparty_name = 'Boba Fett', 
                    amount = 123, 
                    fee = openapi_client.models.update_workflow_metadata_200_response_attributes_fee.update_workflow_metadata_200_response_attributes_fee(
                        currency = 'USD', 
                        amount = 50000, ), 
                    draft = [
                        openapi_client.models.workflow_response_model_attributes_draft_inner.WorkflowResponseModel_attributes_draft_inner(
                            version = 'B1QePArXb', 
                            version_number = 2, 
                            filename = 'file.pdf', 
                            download = '/public/api/v1/workflows/594356b9fbcd7f74006fdf8a/document/rJklwCHQ/download', 
                            last_modified = openapi_client.models.workflow_response_model_attributes_draft_inner_last_modified.WorkflowResponseModel_attributes_draft_inner_lastModified(
                                timestamp = '2016-11-17T00:37:22.318Z', 
                                author = openapi_client.models.author.author(), ), )
                        ], ),
                is_cancelled = False,
                is_complete = False,
                status = 'active',
                created = '2016-11-17T00:37:22.318Z',
                last_updated = '2016-11-17T00:37:22.318Z',
                roles = [
                    openapi_client.models.workflow_response_model_roles_inner.WorkflowResponseModel_roles_inner(
                        id = 'legal', 
                        display_name = 'Legal', 
                        assignees = [
                            openapi_client.models.workflow_response_model_roles_inner_assignees_inner.WorkflowResponseModel_roles_inner_assignees_inner(
                                user_name = 'Boba Fett', 
                                user_id = '63d415e0dd0d828c3a878548', 
                                email = 'bobafett@gmail.com', )
                            ], )
                    ],
                approvals = openapi_client.models.workflow_state_model.WorkflowStateModel(),
                signatures = openapi_client.models.workflow_state_model.WorkflowStateModel(),
                is_revertible_to_review = False,
        )
        """

    def testWorkflowResponseModel(self):
        """Test WorkflowResponseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
