# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.comment_metadata_model_replied_to import CommentMetadataModelRepliedTo

class TestCommentMetadataModelRepliedTo(unittest.TestCase):
    """CommentMetadataModelRepliedTo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommentMetadataModelRepliedTo:
        """Test CommentMetadataModelRepliedTo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommentMetadataModelRepliedTo`
        """
        model = CommentMetadataModelRepliedTo()
        if include_optional:
            return CommentMetadataModelRepliedTo(
                activity_item = 'TODO: unsure this is the right place',
                author = openapi_client.models.activity_author_model.ActivityAuthorModel()
            )
        else:
            return CommentMetadataModelRepliedTo(
        )
        """

    def testCommentMetadataModelRepliedTo(self):
        """Test CommentMetadataModelRepliedTo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
