# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.list_all_workflow_participants200_response import ListAllWorkflowParticipants200Response

class TestListAllWorkflowParticipants200Response(unittest.TestCase):
    """ListAllWorkflowParticipants200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllWorkflowParticipants200Response:
        """Test ListAllWorkflowParticipants200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllWorkflowParticipants200Response`
        """
        model = ListAllWorkflowParticipants200Response()
        if include_optional:
            return ListAllWorkflowParticipants200Response(
                page = 0,
                page_size = 20,
                count = 1,
                list = [
                    openapi_client.models.list_all_workflow_participants_200_response_list_inner.list_all_workflow_participants_200_response_list_inner(
                        user_id = '61968ae4945dcecf4a78cc83', 
                        email = 'boba@intergalactic.com', )
                    ]
            )
        else:
            return ListAllWorkflowParticipants200Response(
        )
        """

    def testListAllWorkflowParticipants200Response(self):
        """Test ListAllWorkflowParticipants200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
