# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.retrieve_attachment_from_email_thread404_response import RetrieveAttachmentFromEmailThread404Response

class TestRetrieveAttachmentFromEmailThread404Response(unittest.TestCase):
    """RetrieveAttachmentFromEmailThread404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RetrieveAttachmentFromEmailThread404Response:
        """Test RetrieveAttachmentFromEmailThread404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RetrieveAttachmentFromEmailThread404Response`
        """
        model = RetrieveAttachmentFromEmailThread404Response()
        if include_optional:
            return RetrieveAttachmentFromEmailThread404Response(
                code = 'NOT_FOUND',
                message = 'attachmentId does not exist',
                param = 'attachmentId'
            )
        else:
            return RetrieveAttachmentFromEmailThread404Response(
        )
        """

    def testRetrieveAttachmentFromEmailThread404Response(self):
        """Test RetrieveAttachmentFromEmailThread404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
