# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.turn_history200_response import TurnHistory200Response

class TestTurnHistory200Response(unittest.TestCase):
    """TurnHistory200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TurnHistory200Response:
        """Test TurnHistory200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TurnHistory200Response`
        """
        model = TurnHistory200Response()
        if include_optional:
            return TurnHistory200Response(
                page = 0,
                page_size = 20,
                count = 42,
                list = [
                    openapi_client.models.turn_history_200_response_list_inner.turn_history_200_response_list_inner(
                        turn_party = 'internal', 
                        turn_start_time = '2022-09-20T15:51:54.156Z', 
                        turn_location = 'manual change', 
                        turn_user_id = '5f89b6a5eed2cc6e0b2735d4', 
                        turn_end_time = '2022-09-28T19:21:05.034Z', 
                        turn_number = 1, 
                        turn_user_email = 'baldwin@ironcladhq.com', )
                    ]
            )
        else:
            return TurnHistory200Response(
        )
        """

    def testTurnHistory200Response(self):
        """Test TurnHistory200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
