# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.update_workflow_metadata200_response_schema_amount import UpdateWorkflowMetadata200ResponseSchemaAmount

class TestUpdateWorkflowMetadata200ResponseSchemaAmount(unittest.TestCase):
    """UpdateWorkflowMetadata200ResponseSchemaAmount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWorkflowMetadata200ResponseSchemaAmount:
        """Test UpdateWorkflowMetadata200ResponseSchemaAmount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWorkflowMetadata200ResponseSchemaAmount`
        """
        model = UpdateWorkflowMetadata200ResponseSchemaAmount()
        if include_optional:
            return UpdateWorkflowMetadata200ResponseSchemaAmount(
                type = 'number',
                display_name = 'Example Number Attribute'
            )
        else:
            return UpdateWorkflowMetadata200ResponseSchemaAmount(
        )
        """

    def testUpdateWorkflowMetadata200ResponseSchemaAmount(self):
        """Test UpdateWorkflowMetadata200ResponseSchemaAmount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
