# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update_workflow_metadata200_response_attributes_draft_inner import UpdateWorkflowMetadata200ResponseAttributesDraftInner

class TestUpdateWorkflowMetadata200ResponseAttributesDraftInner(unittest.TestCase):
    """UpdateWorkflowMetadata200ResponseAttributesDraftInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWorkflowMetadata200ResponseAttributesDraftInner:
        """Test UpdateWorkflowMetadata200ResponseAttributesDraftInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWorkflowMetadata200ResponseAttributesDraftInner`
        """
        model = UpdateWorkflowMetadata200ResponseAttributesDraftInner()
        if include_optional:
            return UpdateWorkflowMetadata200ResponseAttributesDraftInner(
                version = 'B1QePArXb',
                filename = 'file.pdf',
                download = '/public/api/v1/workflows/594356b9fbcd7f74006fdf8a/document/rJklwCHQ/download'
            )
        else:
            return UpdateWorkflowMetadata200ResponseAttributesDraftInner(
        )
        """

    def testUpdateWorkflowMetadata200ResponseAttributesDraftInner(self):
        """Test UpdateWorkflowMetadata200ResponseAttributesDraftInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
