# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.create_a_record_request_properties import CreateARecordRequestProperties

class TestCreateARecordRequestProperties(unittest.TestCase):
    """CreateARecordRequestProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateARecordRequestProperties:
        """Test CreateARecordRequestProperties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateARecordRequestProperties`
        """
        model = CreateARecordRequestProperties()
        if include_optional:
            return CreateARecordRequestProperties(
                agreement_date = openapi_client.models.create_a_record_request_properties_agreement_date.create_a_record_request_properties_agreementDate(
                    type = 'date', 
                    value = '', ),
                counterparty_name = openapi_client.models.create_a_record_request_properties_counterparty_name.create_a_record_request_properties_counterpartyName(
                    type = 'string', 
                    value = '', )
            )
        else:
            return CreateARecordRequestProperties(
        )
        """

    def testCreateARecordRequestProperties(self):
        """Test CreateARecordRequestProperties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
