# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.create_a_record_request import CreateARecordRequest

class TestCreateARecordRequest(unittest.TestCase):
    """CreateARecordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateARecordRequest:
        """Test CreateARecordRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateARecordRequest`
        """
        model = CreateARecordRequest()
        if include_optional:
            return CreateARecordRequest(
                type = '',
                name = '',
                properties = openapi_client.models.create_a_record_request_properties.create_a_record_request_properties(
                    agreement_date = openapi_client.models.create_a_record_request_properties_agreement_date.create_a_record_request_properties_agreementDate(
                        type = 'date', 
                        value = '', ), 
                    counterparty_name = openapi_client.models.create_a_record_request_properties_counterparty_name.create_a_record_request_properties_counterpartyName(
                        type = 'string', 
                        value = '', ), ),
                links = [
                    openapi_client.models.record_property_link_model.RecordPropertyLinkModel(
                        record_id = '17009e0d-z2e9-425d-a85b-1cf152773e49', )
                    ],
                parent = openapi_client.models.create_a_record_request_parent.create_a_record_request_parent(
                    record_id = '17009e0d-z2e9-425d-a85b-1cf152773efg', ),
                children = [
                    openapi_client.models.record_property_link_model.RecordPropertyLinkModel(
                        record_id = '17009e0d-z2e9-425d-a85b-1cf152773e49', )
                    ]
            )
        else:
            return CreateARecordRequest(
                type = '',
                name = '',
                properties = openapi_client.models.create_a_record_request_properties.create_a_record_request_properties(
                    agreement_date = openapi_client.models.create_a_record_request_properties_agreement_date.create_a_record_request_properties_agreementDate(
                        type = 'date', 
                        value = '', ), 
                    counterparty_name = openapi_client.models.create_a_record_request_properties_counterparty_name.create_a_record_request_properties_counterpartyName(
                        type = 'string', 
                        value = '', ), ),
        )
        """

    def testCreateARecordRequest(self):
        """Test CreateARecordRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
