# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.list_all_workflow_signers200_response_signers_inner_delegates_inner import ListAllWorkflowSigners200ResponseSignersInnerDelegatesInner

class TestListAllWorkflowSigners200ResponseSignersInnerDelegatesInner(unittest.TestCase):
    """ListAllWorkflowSigners200ResponseSignersInnerDelegatesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllWorkflowSigners200ResponseSignersInnerDelegatesInner:
        """Test ListAllWorkflowSigners200ResponseSignersInnerDelegatesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllWorkflowSigners200ResponseSignersInnerDelegatesInner`
        """
        model = ListAllWorkflowSigners200ResponseSignersInnerDelegatesInner()
        if include_optional:
            return ListAllWorkflowSigners200ResponseSignersInnerDelegatesInner(
                name = 'Kim Lam',
                email = 'kimlam@gmail.com'
            )
        else:
            return ListAllWorkflowSigners200ResponseSignersInnerDelegatesInner(
        )
        """

    def testListAllWorkflowSigners200ResponseSignersInnerDelegatesInner(self):
        """Test ListAllWorkflowSigners200ResponseSignersInnerDelegatesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
