# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update_workflow_metadata200_response_schema_line_items_element_type_schema import UpdateWorkflowMetadata200ResponseSchemaLineItemsElementTypeSchema

class TestUpdateWorkflowMetadata200ResponseSchemaLineItemsElementTypeSchema(unittest.TestCase):
    """UpdateWorkflowMetadata200ResponseSchemaLineItemsElementTypeSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWorkflowMetadata200ResponseSchemaLineItemsElementTypeSchema:
        """Test UpdateWorkflowMetadata200ResponseSchemaLineItemsElementTypeSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWorkflowMetadata200ResponseSchemaLineItemsElementTypeSchema`
        """
        model = UpdateWorkflowMetadata200ResponseSchemaLineItemsElementTypeSchema()
        if include_optional:
            return UpdateWorkflowMetadata200ResponseSchemaLineItemsElementTypeSchema(
                child_attribute = openapi_client.models.update_workflow_metadata_200_response_schema_counterparty_name.update_workflow_metadata_200_response_schema_counterpartyName(
                    type = 'string', 
                    display_name = 'Example String Attribute', ),
                another_child_attribute = openapi_client.models.update_workflow_metadata_200_response_schema_counterparty_name.update_workflow_metadata_200_response_schema_counterpartyName(
                    type = 'string', 
                    display_name = 'Example String Attribute', )
            )
        else:
            return UpdateWorkflowMetadata200ResponseSchemaLineItemsElementTypeSchema(
        )
        """

    def testUpdateWorkflowMetadata200ResponseSchemaLineItemsElementTypeSchema(self):
        """Test UpdateWorkflowMetadata200ResponseSchemaLineItemsElementTypeSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
