# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.bad_request_error_record_id_not_found import BadRequestErrorRecordIDNotFound

class TestBadRequestErrorRecordIDNotFound(unittest.TestCase):
    """BadRequestErrorRecordIDNotFound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BadRequestErrorRecordIDNotFound:
        """Test BadRequestErrorRecordIDNotFound
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BadRequestErrorRecordIDNotFound`
        """
        model = BadRequestErrorRecordIDNotFound()
        if include_optional:
            return BadRequestErrorRecordIDNotFound(
                code = 'NOT_FOUND',
                message = 'couldn't find a record matching the id [SOME_NONEXISTENT_RECORD_ID]'
            )
        else:
            return BadRequestErrorRecordIDNotFound(
        )
        """

    def testBadRequestErrorRecordIDNotFound(self):
        """Test BadRequestErrorRecordIDNotFound"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
