# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.launched_workflow_model_signatures import LaunchedWorkflowModelSignatures

class TestLaunchedWorkflowModelSignatures(unittest.TestCase):
    """LaunchedWorkflowModelSignatures unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LaunchedWorkflowModelSignatures:
        """Test LaunchedWorkflowModelSignatures
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LaunchedWorkflowModelSignatures`
        """
        model = LaunchedWorkflowModelSignatures()
        if include_optional:
            return LaunchedWorkflowModelSignatures(
                state = 'in_progress',
                url = 'https://ironcladapp.com/public/api/v1/workflows/6dac47a10b1242d1f7df688d/signatures'
            )
        else:
            return LaunchedWorkflowModelSignatures(
        )
        """

    def testLaunchedWorkflowModelSignatures(self):
        """Test LaunchedWorkflowModelSignatures"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
