# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.retrieve_import_predictions200_response import RetrieveImportPredictions200Response

class TestRetrieveImportPredictions200Response(unittest.TestCase):
    """RetrieveImportPredictions200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RetrieveImportPredictions200Response:
        """Test RetrieveImportPredictions200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RetrieveImportPredictions200Response`
        """
        model = RetrieveImportPredictions200Response()
        if include_optional:
            return RetrieveImportPredictions200Response(
            )
        else:
            return RetrieveImportPredictions200Response(
        )
        """

    def testRetrieveImportPredictions200Response(self):
        """Test RetrieveImportPredictions200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
