# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.outbound_attachment_model import OutboundAttachmentModel

class TestOutboundAttachmentModel(unittest.TestCase):
    """OutboundAttachmentModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutboundAttachmentModel:
        """Test OutboundAttachmentModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutboundAttachmentModel`
        """
        model = OutboundAttachmentModel()
        if include_optional:
            return OutboundAttachmentModel(
                filename = 'attachment.pdf',
                content_type = 'application/pdf',
                download = '/public/api/v1/workflows/6013609108b8f070cee94fc1/document/XZ9j0cHGA/download'
            )
        else:
            return OutboundAttachmentModel(
        )
        """

    def testOutboundAttachmentModel(self):
        """Test OutboundAttachmentModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
