# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.creator_id_model import CreatorIdModel

class TestCreatorIdModel(unittest.TestCase):
    """CreatorIdModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatorIdModel:
        """Test CreatorIdModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatorIdModel`
        """
        model = CreatorIdModel()
        if include_optional:
            return CreatorIdModel(
                type = 'id',
                id = 'abcd1234'
            )
        else:
            return CreatorIdModel(
        )
        """

    def testCreatorIdModel(self):
        """Test CreatorIdModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
