# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.revert_to_review403_response import RevertToReview403Response

class TestRevertToReview403Response(unittest.TestCase):
    """RevertToReview403Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RevertToReview403Response:
        """Test RevertToReview403Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RevertToReview403Response`
        """
        model = RevertToReview403Response()
        if include_optional:
            return RevertToReview403Response(
                code = 'FORBIDDEN',
                message = 'user is not a participant on the workflow',
                param = 'user'
            )
        else:
            return RevertToReview403Response(
        )
        """

    def testRevertToReview403Response(self):
        """Test RevertToReview403Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
