# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.workflow_response_model_creator import WorkflowResponseModelCreator

class TestWorkflowResponseModelCreator(unittest.TestCase):
    """WorkflowResponseModelCreator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowResponseModelCreator:
        """Test WorkflowResponseModelCreator
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowResponseModelCreator`
        """
        model = WorkflowResponseModelCreator()
        if include_optional:
            return WorkflowResponseModelCreator(
                id = '63d415e0dd0d828c3a878548',
                display_name = 'Boba Fett',
                email = 'fett@intergalactic.com',
                title = 'Director',
                username = 'fett@intergalactic.com',
                metadata = {}
            )
        else:
            return WorkflowResponseModelCreator(
                id = '63d415e0dd0d828c3a878548',
                display_name = 'Boba Fett',
                email = 'fett@intergalactic.com',
                title = 'Director',
                username = 'fett@intergalactic.com',
                metadata = {},
        )
        """

    def testWorkflowResponseModelCreator(self):
        """Test WorkflowResponseModelCreator"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
