# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_all_workflow_participants200_response_list_inner import ListAllWorkflowParticipants200ResponseListInner

class TestListAllWorkflowParticipants200ResponseListInner(unittest.TestCase):
    """ListAllWorkflowParticipants200ResponseListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllWorkflowParticipants200ResponseListInner:
        """Test ListAllWorkflowParticipants200ResponseListInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllWorkflowParticipants200ResponseListInner`
        """
        model = ListAllWorkflowParticipants200ResponseListInner()
        if include_optional:
            return ListAllWorkflowParticipants200ResponseListInner(
                user_id = '61968ae4945dcecf4a78cc83',
                email = 'boba@intergalactic.com'
            )
        else:
            return ListAllWorkflowParticipants200ResponseListInner(
        )
        """

    def testListAllWorkflowParticipants200ResponseListInner(self):
        """Test ListAllWorkflowParticipants200ResponseListInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
