# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update_workflow_approval400_response import UpdateWorkflowApproval400Response

class TestUpdateWorkflowApproval400Response(unittest.TestCase):
    """UpdateWorkflowApproval400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWorkflowApproval400Response:
        """Test UpdateWorkflowApproval400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWorkflowApproval400Response`
        """
        model = UpdateWorkflowApproval400Response()
        if include_optional:
            return UpdateWorkflowApproval400Response(
                code = 'INVALID_PARAM',
                message = 'This role does not exist in this workflow',
                param = 'approval'
            )
        else:
            return UpdateWorkflowApproval400Response(
        )
        """

    def testUpdateWorkflowApproval400Response(self):
        """Test UpdateWorkflowApproval400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
