# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.list_all_records_metadata200_response_record_types_contract import ListAllRecordsMetadata200ResponseRecordTypesContract

class TestListAllRecordsMetadata200ResponseRecordTypesContract(unittest.TestCase):
    """ListAllRecordsMetadata200ResponseRecordTypesContract unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllRecordsMetadata200ResponseRecordTypesContract:
        """Test ListAllRecordsMetadata200ResponseRecordTypesContract
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllRecordsMetadata200ResponseRecordTypesContract`
        """
        model = ListAllRecordsMetadata200ResponseRecordTypesContract()
        if include_optional:
            return ListAllRecordsMetadata200ResponseRecordTypesContract(
                display_name = 'Contract'
            )
        else:
            return ListAllRecordsMetadata200ResponseRecordTypesContract(
        )
        """

    def testListAllRecordsMetadata200ResponseRecordTypesContract(self):
        """Test ListAllRecordsMetadata200ResponseRecordTypesContract"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
