# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.create_a_record_request_properties_counterparty_name import CreateARecordRequestPropertiesCounterpartyName

class TestCreateARecordRequestPropertiesCounterpartyName(unittest.TestCase):
    """CreateARecordRequestPropertiesCounterpartyName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateARecordRequestPropertiesCounterpartyName:
        """Test CreateARecordRequestPropertiesCounterpartyName
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateARecordRequestPropertiesCounterpartyName`
        """
        model = CreateARecordRequestPropertiesCounterpartyName()
        if include_optional:
            return CreateARecordRequestPropertiesCounterpartyName(
                type = 'string',
                value = ''
            )
        else:
            return CreateARecordRequestPropertiesCounterpartyName(
        )
        """

    def testCreateARecordRequestPropertiesCounterpartyName(self):
        """Test CreateARecordRequestPropertiesCounterpartyName"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
