# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.outbound_email_response_email_opened_timestamps_inner import OutboundEmailResponseEmailOpenedTimestampsInner

class TestOutboundEmailResponseEmailOpenedTimestampsInner(unittest.TestCase):
    """OutboundEmailResponseEmailOpenedTimestampsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutboundEmailResponseEmailOpenedTimestampsInner:
        """Test OutboundEmailResponseEmailOpenedTimestampsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutboundEmailResponseEmailOpenedTimestampsInner`
        """
        model = OutboundEmailResponseEmailOpenedTimestampsInner()
        if include_optional:
            return OutboundEmailResponseEmailOpenedTimestampsInner(
                email = 'david@boba.com',
                opened = True
            )
        else:
            return OutboundEmailResponseEmailOpenedTimestampsInner(
        )
        """

    def testOutboundEmailResponseEmailOpenedTimestampsInner(self):
        """Test OutboundEmailResponseEmailOpenedTimestampsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
