# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_all_records_metadata200_response_properties_agreement_date import ListAllRecordsMetadata200ResponsePropertiesAgreementDate

class TestListAllRecordsMetadata200ResponsePropertiesAgreementDate(unittest.TestCase):
    """ListAllRecordsMetadata200ResponsePropertiesAgreementDate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllRecordsMetadata200ResponsePropertiesAgreementDate:
        """Test ListAllRecordsMetadata200ResponsePropertiesAgreementDate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllRecordsMetadata200ResponsePropertiesAgreementDate`
        """
        model = ListAllRecordsMetadata200ResponsePropertiesAgreementDate()
        if include_optional:
            return ListAllRecordsMetadata200ResponsePropertiesAgreementDate(
                display_name = 'Agreement Date',
                type = 'date',
                visible = True
            )
        else:
            return ListAllRecordsMetadata200ResponsePropertiesAgreementDate(
        )
        """

    def testListAllRecordsMetadata200ResponsePropertiesAgreementDate(self):
        """Test ListAllRecordsMetadata200ResponsePropertiesAgreementDate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
