# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.launched_workflow_model_creator import LaunchedWorkflowModelCreator

class TestLaunchedWorkflowModelCreator(unittest.TestCase):
    """LaunchedWorkflowModelCreator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LaunchedWorkflowModelCreator:
        """Test LaunchedWorkflowModelCreator
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LaunchedWorkflowModelCreator`
        """
        model = LaunchedWorkflowModelCreator()
        if include_optional:
            return LaunchedWorkflowModelCreator(
                id = '63d415e0dd0d828c3a878548',
                email = 'fett@intergalactic.com',
                display_name = 'Boba Fett'
            )
        else:
            return LaunchedWorkflowModelCreator(
        )
        """

    def testLaunchedWorkflowModelCreator(self):
        """Test LaunchedWorkflowModelCreator"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
