# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_all_records_metadata200_response_properties import ListAllRecordsMetadata200ResponseProperties

class TestListAllRecordsMetadata200ResponseProperties(unittest.TestCase):
    """ListAllRecordsMetadata200ResponseProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllRecordsMetadata200ResponseProperties:
        """Test ListAllRecordsMetadata200ResponseProperties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllRecordsMetadata200ResponseProperties`
        """
        model = ListAllRecordsMetadata200ResponseProperties()
        if include_optional:
            return ListAllRecordsMetadata200ResponseProperties(
                additional_notes = openapi_client.models.list_all_records_metadata_200_response_properties_additional_notes.list_all_records_metadata_200_response_properties_additionalNotes(
                    display_name = 'Additional Notes', 
                    type = 'string', 
                    visible = True, ),
                agreement_date = openapi_client.models.list_all_records_metadata_200_response_properties_agreement_date.list_all_records_metadata_200_response_properties_agreementDate(
                    display_name = 'Agreement Date', 
                    type = 'date', 
                    visible = True, ),
                workflow_id = openapi_client.models.list_all_records_metadata_200_response_properties_workflow_id.list_all_records_metadata_200_response_properties_workflowId(
                    display_name = 'Workflow ID', 
                    type = 'string', 
                    visible = True, )
            )
        else:
            return ListAllRecordsMetadata200ResponseProperties(
        )
        """

    def testListAllRecordsMetadata200ResponseProperties(self):
        """Test ListAllRecordsMetadata200ResponseProperties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
