# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.list_all_workflow_approvals200_response_roles_inner_assignees_inner import ListAllWorkflowApprovals200ResponseRolesInnerAssigneesInner

class TestListAllWorkflowApprovals200ResponseRolesInnerAssigneesInner(unittest.TestCase):
    """ListAllWorkflowApprovals200ResponseRolesInnerAssigneesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllWorkflowApprovals200ResponseRolesInnerAssigneesInner:
        """Test ListAllWorkflowApprovals200ResponseRolesInnerAssigneesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllWorkflowApprovals200ResponseRolesInnerAssigneesInner`
        """
        model = ListAllWorkflowApprovals200ResponseRolesInnerAssigneesInner()
        if include_optional:
            return ListAllWorkflowApprovals200ResponseRolesInnerAssigneesInner(
                user_name = 'Boba Fett',
                user_id = '63d415e0dd0d828c3a878548',
                email = 'bobafett@gmail.com'
            )
        else:
            return ListAllWorkflowApprovals200ResponseRolesInnerAssigneesInner(
        )
        """

    def testListAllWorkflowApprovals200ResponseRolesInnerAssigneesInner(self):
        """Test ListAllWorkflowApprovals200ResponseRolesInnerAssigneesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
