# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_a_smart_import_record200_response import CreateASmartImportRecord200Response

class TestCreateASmartImportRecord200Response(unittest.TestCase):
    """CreateASmartImportRecord200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateASmartImportRecord200Response:
        """Test CreateASmartImportRecord200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateASmartImportRecord200Response`
        """
        model = CreateASmartImportRecord200Response()
        if include_optional:
            return CreateASmartImportRecord200Response(
                record_id = '17fe582d-e1e0-4000-bf65-3d2ec2c500a4',
                import_id = '55ez635d-f2g9-5419-gs34-8h1jx4s733q9',
                remaining_credits = 50
            )
        else:
            return CreateASmartImportRecord200Response(
        )
        """

    def testCreateASmartImportRecord200Response(self):
        """Test CreateASmartImportRecord200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
