# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_an_attachment_on_a_record400_response import CreateAnAttachmentOnARecord400Response

class TestCreateAnAttachmentOnARecord400Response(unittest.TestCase):
    """CreateAnAttachmentOnARecord400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAnAttachmentOnARecord400Response:
        """Test CreateAnAttachmentOnARecord400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAnAttachmentOnARecord400Response`
        """
        model = CreateAnAttachmentOnARecord400Response()
        if include_optional:
            return CreateAnAttachmentOnARecord400Response(
                code = 'INVALID_PARAM',
                message = 'missing required form-data part 'metadata'',
                param = 'metadata'
            )
        else:
            return CreateAnAttachmentOnARecord400Response(
        )
        """

    def testCreateAnAttachmentOnARecord400Response(self):
        """Test CreateAnAttachmentOnARecord400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
