# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_create_a_webhook(self) -> None:
        """Test case for create_a_webhook

        Create a Webhook
        """
        pass

    def test_delete_a_webhook(self) -> None:
        """Test case for delete_a_webhook

        Delete a Webhook
        """
        pass

    def test_list_all_webhooks(self) -> None:
        """Test case for list_all_webhooks

        List All Webhooks
        """
        pass

    def test_retrieve_a_webhook(self) -> None:
        """Test case for retrieve_a_webhook

        Retrieve a Webhook
        """
        pass

    def test_retrieve_webhook_verification_key(self) -> None:
        """Test case for retrieve_webhook_verification_key

        Retrieve Webhook Verification Key
        """
        pass

    def test_update_a_webhook(self) -> None:
        """Test case for update_a_webhook

        Update a Webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
