# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.record_model_attachments import RecordModelAttachments

class TestRecordModelAttachments(unittest.TestCase):
    """RecordModelAttachments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordModelAttachments:
        """Test RecordModelAttachments
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordModelAttachments`
        """
        model = RecordModelAttachments()
        if include_optional:
            return RecordModelAttachments(
                signed_copy = openapi_client.models.record_model_attachments_signed_copy.RecordModel_attachments_signedCopy(
                    filename = '2018-05-08 - Doe, Jane - Consulting Agreement.pdf', 
                    content_type = 'application/json', 
                    href = 'https://ironcladapp.com/public/api/v1/records/22e2ff72-56a1-4711-a4ca-41328d311e9f/attachments/signedCopy', )
            )
        else:
            return RecordModelAttachments(
        )
        """

    def testRecordModelAttachments(self):
        """Test RecordModelAttachments"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
