# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.bad_request_error_record_not_found import BadRequestErrorRecordNotFound

class TestBadRequestErrorRecordNotFound(unittest.TestCase):
    """BadRequestErrorRecordNotFound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BadRequestErrorRecordNotFound:
        """Test BadRequestErrorRecordNotFound
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BadRequestErrorRecordNotFound`
        """
        model = BadRequestErrorRecordNotFound()
        if include_optional:
            return BadRequestErrorRecordNotFound(
                code = 'NOT_FOUND',
                message = 'couldn't find a record matching the id workflow:6346f76fb8fc01d2b43e7c15a'
            )
        else:
            return BadRequestErrorRecordNotFound(
        )
        """

    def testBadRequestErrorRecordNotFound(self):
        """Test BadRequestErrorRecordNotFound"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
