# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update_workflow_metadata_request import UpdateWorkflowMetadataRequest

class TestUpdateWorkflowMetadataRequest(unittest.TestCase):
    """UpdateWorkflowMetadataRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWorkflowMetadataRequest:
        """Test UpdateWorkflowMetadataRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWorkflowMetadataRequest`
        """
        model = UpdateWorkflowMetadataRequest()
        if include_optional:
            return UpdateWorkflowMetadataRequest(
                updates = [
                    openapi_client.models.update_workflow_metadata_request_updates_inner.update_workflow_metadata_request_updates_inner(
                        action = 'set', 
                        path = 'counterpartyName', 
                        value = 'Example Company', )
                    ],
                comment = 'Changing attribute on a Workflow.'
            )
        else:
            return UpdateWorkflowMetadataRequest(
                updates = [
                    openapi_client.models.update_workflow_metadata_request_updates_inner.update_workflow_metadata_request_updates_inner(
                        action = 'set', 
                        path = 'counterpartyName', 
                        value = 'Example Company', )
                    ],
        )
        """

    def testUpdateWorkflowMetadataRequest(self):
        """Test UpdateWorkflowMetadataRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
