# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.activity_author_model_one_of1 import ActivityAuthorModelOneOf1

class TestActivityAuthorModelOneOf1(unittest.TestCase):
    """ActivityAuthorModelOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActivityAuthorModelOneOf1:
        """Test ActivityAuthorModelOneOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActivityAuthorModelOneOf1`
        """
        model = ActivityAuthorModelOneOf1()
        if include_optional:
            return ActivityAuthorModelOneOf1(
                type = 'system',
                display_name = 'Ironclad'
            )
        else:
            return ActivityAuthorModelOneOf1(
        )
        """

    def testActivityAuthorModelOneOf1(self):
        """Test ActivityAuthorModelOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
