# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.list_all_records_metadata200_response_attachments_signed_copy import ListAllRecordsMetadata200ResponseAttachmentsSignedCopy

class TestListAllRecordsMetadata200ResponseAttachmentsSignedCopy(unittest.TestCase):
    """ListAllRecordsMetadata200ResponseAttachmentsSignedCopy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllRecordsMetadata200ResponseAttachmentsSignedCopy:
        """Test ListAllRecordsMetadata200ResponseAttachmentsSignedCopy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllRecordsMetadata200ResponseAttachmentsSignedCopy`
        """
        model = ListAllRecordsMetadata200ResponseAttachmentsSignedCopy()
        if include_optional:
            return ListAllRecordsMetadata200ResponseAttachmentsSignedCopy(
                display_name = 'Signed PDF'
            )
        else:
            return ListAllRecordsMetadata200ResponseAttachmentsSignedCopy(
        )
        """

    def testListAllRecordsMetadata200ResponseAttachmentsSignedCopy(self):
        """Test ListAllRecordsMetadata200ResponseAttachmentsSignedCopy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
