# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.workflow_response_model_attributes import WorkflowResponseModelAttributes

class TestWorkflowResponseModelAttributes(unittest.TestCase):
    """WorkflowResponseModelAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowResponseModelAttributes:
        """Test WorkflowResponseModelAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowResponseModelAttributes`
        """
        model = WorkflowResponseModelAttributes()
        if include_optional:
            return WorkflowResponseModelAttributes(
                counterparty_name = 'Boba Fett',
                amount = 123,
                fee = openapi_client.models.update_workflow_metadata_200_response_attributes_fee.update_workflow_metadata_200_response_attributes_fee(
                    currency = 'USD', 
                    amount = 50000, ),
                draft = [
                    openapi_client.models.workflow_response_model_attributes_draft_inner.WorkflowResponseModel_attributes_draft_inner(
                        version = 'B1QePArXb', 
                        version_number = 2, 
                        filename = 'file.pdf', 
                        download = '/public/api/v1/workflows/594356b9fbcd7f74006fdf8a/document/rJklwCHQ/download', 
                        last_modified = openapi_client.models.workflow_response_model_attributes_draft_inner_last_modified.WorkflowResponseModel_attributes_draft_inner_lastModified(
                            timestamp = '2016-11-17T00:37:22.318Z', 
                            author = openapi_client.models.author.author(), ), )
                    ]
            )
        else:
            return WorkflowResponseModelAttributes(
        )
        """

    def testWorkflowResponseModelAttributes(self):
        """Test WorkflowResponseModelAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
