# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.launched_workflow_model_approvals import LaunchedWorkflowModelApprovals

class TestLaunchedWorkflowModelApprovals(unittest.TestCase):
    """LaunchedWorkflowModelApprovals unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LaunchedWorkflowModelApprovals:
        """Test LaunchedWorkflowModelApprovals
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LaunchedWorkflowModelApprovals`
        """
        model = LaunchedWorkflowModelApprovals()
        if include_optional:
            return LaunchedWorkflowModelApprovals(
                state = 'in_progress'
            )
        else:
            return LaunchedWorkflowModelApprovals(
        )
        """

    def testLaunchedWorkflowModelApprovals(self):
        """Test LaunchedWorkflowModelApprovals"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
