# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.api.records_api import RecordsApi


class TestRecordsApi(unittest.TestCase):
    """RecordsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecordsApi()

    def tearDown(self) -> None:
        pass

    def test_create_a_record(self) -> None:
        """Test case for create_a_record

        Create a Record
        """
        pass

    def test_create_a_smart_import_record(self) -> None:
        """Test case for create_a_smart_import_record

        Create a Smart Import Record
        """
        pass

    def test_create_a_smart_import_record_to_import(self) -> None:
        """Test case for create_a_smart_import_record_to_import

        Upload a Smart Import Record to an existing Import
        """
        pass

    def test_create_an_attachment_on_a_record(self) -> None:
        """Test case for create_an_attachment_on_a_record

        Create an Attachment on a Record
        """
        pass

    def test_delete_a_record(self) -> None:
        """Test case for delete_a_record

        Delete a Record
        """
        pass

    def test_delete_an_attachment_on_a_record(self) -> None:
        """Test case for delete_an_attachment_on_a_record

        Delete an Attachment on a Record
        """
        pass

    def test_list_all_records(self) -> None:
        """Test case for list_all_records

        List All Records
        """
        pass

    def test_list_all_records_metadata(self) -> None:
        """Test case for list_all_records_metadata

        Retrieve Records Schema
        """
        pass

    def test_replace_a_record(self) -> None:
        """Test case for replace_a_record

        Replace a Record
        """
        pass

    def test_retrieve_a_record(self) -> None:
        """Test case for retrieve_a_record

        Retrieve a Record
        """
        pass

    def test_retrieve_an_attachment_on_a_record(self) -> None:
        """Test case for retrieve_an_attachment_on_a_record

        Retrieve an Attachment on a Record
        """
        pass

    def test_retrieve_import_predictions(self) -> None:
        """Test case for retrieve_import_predictions

        Retrieve Predictions
        """
        pass

    def test_retrieve_xlsx_export_file_of_all_records(self) -> None:
        """Test case for retrieve_xlsx_export_file_of_all_records

        Retrieve XLSX Export File of Records
        """
        pass

    def test_update_record_metadata(self) -> None:
        """Test case for update_record_metadata

        Update Record Metadata
        """
        pass


if __name__ == '__main__':
    unittest.main()
