# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_all_records_metadata200_response_record_types import ListAllRecordsMetadata200ResponseRecordTypes

class TestListAllRecordsMetadata200ResponseRecordTypes(unittest.TestCase):
    """ListAllRecordsMetadata200ResponseRecordTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllRecordsMetadata200ResponseRecordTypes:
        """Test ListAllRecordsMetadata200ResponseRecordTypes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllRecordsMetadata200ResponseRecordTypes`
        """
        model = ListAllRecordsMetadata200ResponseRecordTypes()
        if include_optional:
            return ListAllRecordsMetadata200ResponseRecordTypes(
                contract = openapi_client.models.list_all_records_metadata_200_response_record_types_contract.list_all_records_metadata_200_response_recordTypes_contract(
                    display_name = 'Contract', )
            )
        else:
            return ListAllRecordsMetadata200ResponseRecordTypes(
        )
        """

    def testListAllRecordsMetadata200ResponseRecordTypes(self):
        """Test ListAllRecordsMetadata200ResponseRecordTypes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
