# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.webhook_event_type_value import WebhookEventTypeValue

class TestWebhookEventTypeValue(unittest.TestCase):
    """WebhookEventTypeValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebhookEventTypeValue(self):
        """Test WebhookEventTypeValue"""
        # inst = WebhookEventTypeValue()

if __name__ == '__main__':
    unittest.main()
