# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.workflow_launch_status import WorkflowLaunchStatus

class TestWorkflowLaunchStatus(unittest.TestCase):
    """WorkflowLaunchStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowLaunchStatus:
        """Test WorkflowLaunchStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowLaunchStatus`
        """
        model = WorkflowLaunchStatus()
        if include_optional:
            return WorkflowLaunchStatus(
                status = 'in_progress',
                request_payload = openapi_client.models.workflow_request_model.WorkflowRequestModel(
                    template = '600b296c3e15a234ab88f884', 
                    creator = openapi_client.models.creator_email_model.CreatorEmailModel(
                        type = 'email', 
                        email = 'example@example.com', ), 
                    attributes = openapi_client.models.attributes_model.AttributesModel(
                        counterparty_name = 'Example Company', 
                        draft = [
                            openapi_client.models.attributes_model_draft_inner.AttributesModel_draft_inner(
                                url = 'https://www.law.berkeley.edu/wp-content/uploads/2018/12/Resume-Samples-1.pdf', )
                            ], 
                        paper_source = 'Counterparty paper', ), ),
                workflow_urls = openapi_client.models.workflow_async_launch_success_response_workflow_urls.WorkflowAsyncLaunchSuccessResponse_workflowUrls(
                    browser_url = 'http://ironcladapp.com/workflows/6013609108b8f070cee94fc1', 
                    api_url = 'http://ironcladapp.com/public/api/v1/workflows/6013609108b8f070cee94fc1', ),
                workflow = openapi_client.models.launched_workflow_model.LaunchedWorkflowModel(
                    id = '6013609108b8f070cee94fc1', 
                    ironclad_id = 'IC-1', 
                    title = 'Consulting Agreement with Jane Doe', 
                    template = '600b296c3e15a234ab88f884', 
                    step = 'Review', 
                    schema = openapi_client.models.attributes_model.AttributesModel(
                        counterparty_name = 'Example Company', 
                        draft = [
                            openapi_client.models.attributes_model_draft_inner.AttributesModel_draft_inner(
                                url = 'https://www.law.berkeley.edu/wp-content/uploads/2018/12/Resume-Samples-1.pdf', )
                            ], 
                        paper_source = 'Counterparty paper', ), 
                    is_cancelled = False, 
                    is_complete = False, 
                    status = 'active', 
                    creator = openapi_client.models.launched_workflow_model_creator.LaunchedWorkflowModel_creator(
                        id = '63d415e0dd0d828c3a878548', 
                        email = 'fett@intergalactic.com', 
                        display_name = 'Boba Fett', ), 
                    created = '2016-11-17T00:37:22.318Z', 
                    last_updated = '2016-11-17T00:37:42.318Z', 
                    roles = [
                        openapi_client.models.workflow_role_model.WorkflowRoleModel(
                            id = 'legal', 
                            display_name = 'Legal', 
                            assignees = [
                                openapi_client.models.workflow_role_assignee_model.WorkflowRoleAssigneeModel(
                                    user_name = 'Boba Fett', 
                                    user_id = '63d415e0dd0d828c3a878548', 
                                    email = 'bobafett@gmail.com', )
                                ], )
                        ], 
                    approvals = openapi_client.models.launched_workflow_model_approvals.LaunchedWorkflowModel_approvals(
                        state = 'in_progress', ), 
                    signatures = openapi_client.models.launched_workflow_model_signatures.LaunchedWorkflowModel_signatures(
                        state = 'in_progress', 
                        url = 'https://ironcladapp.com/public/api/v1/workflows/6dac47a10b1242d1f7df688d/signatures', ), 
                    record_ids = [
                        '715f1e37-292f-4e6c-8b48-c07e1b68bccd'
                        ], 
                    is_revertible_to_review = False, ),
                error = ''
            )
        else:
            return WorkflowLaunchStatus(
                status = 'in_progress',
                request_payload = openapi_client.models.workflow_request_model.WorkflowRequestModel(
                    template = '600b296c3e15a234ab88f884', 
                    creator = openapi_client.models.creator_email_model.CreatorEmailModel(
                        type = 'email', 
                        email = 'example@example.com', ), 
                    attributes = openapi_client.models.attributes_model.AttributesModel(
                        counterparty_name = 'Example Company', 
                        draft = [
                            openapi_client.models.attributes_model_draft_inner.AttributesModel_draft_inner(
                                url = 'https://www.law.berkeley.edu/wp-content/uploads/2018/12/Resume-Samples-1.pdf', )
                            ], 
                        paper_source = 'Counterparty paper', ), ),
                workflow_urls = openapi_client.models.workflow_async_launch_success_response_workflow_urls.WorkflowAsyncLaunchSuccessResponse_workflowUrls(
                    browser_url = 'http://ironcladapp.com/workflows/6013609108b8f070cee94fc1', 
                    api_url = 'http://ironcladapp.com/public/api/v1/workflows/6013609108b8f070cee94fc1', ),
                workflow = openapi_client.models.launched_workflow_model.LaunchedWorkflowModel(
                    id = '6013609108b8f070cee94fc1', 
                    ironclad_id = 'IC-1', 
                    title = 'Consulting Agreement with Jane Doe', 
                    template = '600b296c3e15a234ab88f884', 
                    step = 'Review', 
                    schema = openapi_client.models.attributes_model.AttributesModel(
                        counterparty_name = 'Example Company', 
                        draft = [
                            openapi_client.models.attributes_model_draft_inner.AttributesModel_draft_inner(
                                url = 'https://www.law.berkeley.edu/wp-content/uploads/2018/12/Resume-Samples-1.pdf', )
                            ], 
                        paper_source = 'Counterparty paper', ), 
                    is_cancelled = False, 
                    is_complete = False, 
                    status = 'active', 
                    creator = openapi_client.models.launched_workflow_model_creator.LaunchedWorkflowModel_creator(
                        id = '63d415e0dd0d828c3a878548', 
                        email = 'fett@intergalactic.com', 
                        display_name = 'Boba Fett', ), 
                    created = '2016-11-17T00:37:22.318Z', 
                    last_updated = '2016-11-17T00:37:42.318Z', 
                    roles = [
                        openapi_client.models.workflow_role_model.WorkflowRoleModel(
                            id = 'legal', 
                            display_name = 'Legal', 
                            assignees = [
                                openapi_client.models.workflow_role_assignee_model.WorkflowRoleAssigneeModel(
                                    user_name = 'Boba Fett', 
                                    user_id = '63d415e0dd0d828c3a878548', 
                                    email = 'bobafett@gmail.com', )
                                ], )
                        ], 
                    approvals = openapi_client.models.launched_workflow_model_approvals.LaunchedWorkflowModel_approvals(
                        state = 'in_progress', ), 
                    signatures = openapi_client.models.launched_workflow_model_signatures.LaunchedWorkflowModel_signatures(
                        state = 'in_progress', 
                        url = 'https://ironcladapp.com/public/api/v1/workflows/6dac47a10b1242d1f7df688d/signatures', ), 
                    record_ids = [
                        '715f1e37-292f-4e6c-8b48-c07e1b68bccd'
                        ], 
                    is_revertible_to_review = False, ),
                error = '',
        )
        """

    def testWorkflowLaunchStatus(self):
        """Test WorkflowLaunchStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
