# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update_workflow_metadata400_response import UpdateWorkflowMetadata400Response

class TestUpdateWorkflowMetadata400Response(unittest.TestCase):
    """UpdateWorkflowMetadata400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWorkflowMetadata400Response:
        """Test UpdateWorkflowMetadata400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWorkflowMetadata400Response`
        """
        model = UpdateWorkflowMetadata400Response()
        if include_optional:
            return UpdateWorkflowMetadata400Response(
                code = '',
                message = '',
                param = ''
            )
        else:
            return UpdateWorkflowMetadata400Response(
        )
        """

    def testUpdateWorkflowMetadata400Response(self):
        """Test UpdateWorkflowMetadata400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
