# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update_workflow_metadata_request_updates_inner import UpdateWorkflowMetadataRequestUpdatesInner

class TestUpdateWorkflowMetadataRequestUpdatesInner(unittest.TestCase):
    """UpdateWorkflowMetadataRequestUpdatesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWorkflowMetadataRequestUpdatesInner:
        """Test UpdateWorkflowMetadataRequestUpdatesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWorkflowMetadataRequestUpdatesInner`
        """
        model = UpdateWorkflowMetadataRequestUpdatesInner()
        if include_optional:
            return UpdateWorkflowMetadataRequestUpdatesInner(
                action = 'set',
                path = 'counterpartyName',
                value = 'Example Company'
            )
        else:
            return UpdateWorkflowMetadataRequestUpdatesInner(
                action = 'set',
                path = 'counterpartyName',
        )
        """

    def testUpdateWorkflowMetadataRequestUpdatesInner(self):
        """Test UpdateWorkflowMetadataRequestUpdatesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
