# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.record_model_properties import RecordModelProperties

class TestRecordModelProperties(unittest.TestCase):
    """RecordModelProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordModelProperties:
        """Test RecordModelProperties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordModelProperties`
        """
        model = RecordModelProperties()
        if include_optional:
            return RecordModelProperties(
                agreement_date = openapi_client.models.record_model_properties_agreement_date.RecordModel_properties_agreementDate(
                    type = 'date', 
                    value = '2018-05-08T00:00:00-07:00', ),
                counterparty_name = openapi_client.models.record_model_properties_counterparty_name.RecordModel_properties_counterpartyName(
                    type = 'string', 
                    value = 'Jane Doe', ),
                counterparty_email = openapi_client.models.record_model_properties_counterparty_email.RecordModel_properties_counterpartyEmail(
                    type = 'email', 
                    value = 'jane.doe@test.com', ),
                hourly_rate = openapi_client.models.record_model_properties_hourly_rate.RecordModel_properties_hourlyRate(
                    type = 'monetaryAmount', 
                    value = openapi_client.models.record_model_properties_hourly_rate_value.RecordModel_properties_hourlyRate_value(
                        amount = 100, 
                        currency = 'USD', ), )
            )
        else:
            return RecordModelProperties(
        )
        """

    def testRecordModelProperties(self):
        """Test RecordModelProperties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
