# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.revert_to_review400_response import RevertToReview400Response

class TestRevertToReview400Response(unittest.TestCase):
    """RevertToReview400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RevertToReview400Response:
        """Test RevertToReview400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RevertToReview400Response`
        """
        model = RevertToReview400Response()
        if include_optional:
            return RevertToReview400Response(
                code = 'INVALID_STATE',
                message = 'workflow cannot be reverted to review as it is not in the sign stage',
                param = 'user'
            )
        else:
            return RevertToReview400Response(
        )
        """

    def testRevertToReview400Response(self):
        """Test RevertToReview400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
