# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.update_workflow_metadata200_response_schema_counterparty_name import UpdateWorkflowMetadata200ResponseSchemaCounterpartyName

class TestUpdateWorkflowMetadata200ResponseSchemaCounterpartyName(unittest.TestCase):
    """UpdateWorkflowMetadata200ResponseSchemaCounterpartyName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWorkflowMetadata200ResponseSchemaCounterpartyName:
        """Test UpdateWorkflowMetadata200ResponseSchemaCounterpartyName
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWorkflowMetadata200ResponseSchemaCounterpartyName`
        """
        model = UpdateWorkflowMetadata200ResponseSchemaCounterpartyName()
        if include_optional:
            return UpdateWorkflowMetadata200ResponseSchemaCounterpartyName(
                type = 'string',
                display_name = 'Example String Attribute'
            )
        else:
            return UpdateWorkflowMetadata200ResponseSchemaCounterpartyName(
        )
        """

    def testUpdateWorkflowMetadata200ResponseSchemaCounterpartyName(self):
        """Test UpdateWorkflowMetadata200ResponseSchemaCounterpartyName"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
