# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.update_workflow_metadata200_response_schema_line_items_element_type import UpdateWorkflowMetadata200ResponseSchemaLineItemsElementType

class TestUpdateWorkflowMetadata200ResponseSchemaLineItemsElementType(unittest.TestCase):
    """UpdateWorkflowMetadata200ResponseSchemaLineItemsElementType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWorkflowMetadata200ResponseSchemaLineItemsElementType:
        """Test UpdateWorkflowMetadata200ResponseSchemaLineItemsElementType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWorkflowMetadata200ResponseSchemaLineItemsElementType`
        """
        model = UpdateWorkflowMetadata200ResponseSchemaLineItemsElementType()
        if include_optional:
            return UpdateWorkflowMetadata200ResponseSchemaLineItemsElementType(
                type = 'object',
                display_name = 'Example Object Attribute',
                var_schema = openapi_client.models.update_workflow_metadata_200_response_schema_line_items_element_type_schema.update_workflow_metadata_200_response_schema_lineItems_elementType_schema(
                    child_attribute = openapi_client.models.update_workflow_metadata_200_response_schema_counterparty_name.update_workflow_metadata_200_response_schema_counterpartyName(
                        type = 'string', 
                        display_name = 'Example String Attribute', ), 
                    another_child_attribute = openapi_client.models.update_workflow_metadata_200_response_schema_counterparty_name.update_workflow_metadata_200_response_schema_counterpartyName(
                        type = 'string', 
                        display_name = 'Example String Attribute', ), )
            )
        else:
            return UpdateWorkflowMetadata200ResponseSchemaLineItemsElementType(
        )
        """

    def testUpdateWorkflowMetadata200ResponseSchemaLineItemsElementType(self):
        """Test UpdateWorkflowMetadata200ResponseSchemaLineItemsElementType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
