# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.workflow_state_model_one_of2 import WorkflowStateModelOneOf2

class TestWorkflowStateModelOneOf2(unittest.TestCase):
    """WorkflowStateModelOneOf2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowStateModelOneOf2:
        """Test WorkflowStateModelOneOf2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowStateModelOneOf2`
        """
        model = WorkflowStateModelOneOf2()
        if include_optional:
            return WorkflowStateModelOneOf2(
                state = 'in_progress',
                url = 'https://ironcladapp.com/public/api/v1/workflows/22e2ff72-56a1-4711-a4ca-41328d311e9f/approvals'
            )
        else:
            return WorkflowStateModelOneOf2(
                state = 'in_progress',
                url = 'https://ironcladapp.com/public/api/v1/workflows/22e2ff72-56a1-4711-a4ca-41328d311e9f/approvals',
        )
        """

    def testWorkflowStateModelOneOf2(self):
        """Test WorkflowStateModelOneOf2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
