# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_all_records_metadata200_response_properties_additional_notes import ListAllRecordsMetadata200ResponsePropertiesAdditionalNotes

class TestListAllRecordsMetadata200ResponsePropertiesAdditionalNotes(unittest.TestCase):
    """ListAllRecordsMetadata200ResponsePropertiesAdditionalNotes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllRecordsMetadata200ResponsePropertiesAdditionalNotes:
        """Test ListAllRecordsMetadata200ResponsePropertiesAdditionalNotes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllRecordsMetadata200ResponsePropertiesAdditionalNotes`
        """
        model = ListAllRecordsMetadata200ResponsePropertiesAdditionalNotes()
        if include_optional:
            return ListAllRecordsMetadata200ResponsePropertiesAdditionalNotes(
                display_name = 'Additional Notes',
                type = 'string',
                visible = True
            )
        else:
            return ListAllRecordsMetadata200ResponsePropertiesAdditionalNotes(
        )
        """

    def testListAllRecordsMetadata200ResponsePropertiesAdditionalNotes(self):
        """Test ListAllRecordsMetadata200ResponsePropertiesAdditionalNotes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
