# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.workflow_state_model_one_of3 import WorkflowStateModelOneOf3

class TestWorkflowStateModelOneOf3(unittest.TestCase):
    """WorkflowStateModelOneOf3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowStateModelOneOf3:
        """Test WorkflowStateModelOneOf3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowStateModelOneOf3`
        """
        model = WorkflowStateModelOneOf3()
        if include_optional:
            return WorkflowStateModelOneOf3(
                state = 'not_applicable',
                message = 'This workflow has been cancelled'
            )
        else:
            return WorkflowStateModelOneOf3(
                state = 'not_applicable',
                message = 'This workflow has been cancelled',
        )
        """

    def testWorkflowStateModelOneOf3(self):
        """Test WorkflowStateModelOneOf3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
