# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_all_records_metadata200_response_attachments import ListAllRecordsMetadata200ResponseAttachments

class TestListAllRecordsMetadata200ResponseAttachments(unittest.TestCase):
    """ListAllRecordsMetadata200ResponseAttachments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllRecordsMetadata200ResponseAttachments:
        """Test ListAllRecordsMetadata200ResponseAttachments
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllRecordsMetadata200ResponseAttachments`
        """
        model = ListAllRecordsMetadata200ResponseAttachments()
        if include_optional:
            return ListAllRecordsMetadata200ResponseAttachments(
                signed_copy = openapi_client.models.list_all_records_metadata_200_response_attachments_signed_copy.list_all_records_metadata_200_response_attachments_signedCopy(
                    display_name = 'Signed PDF', )
            )
        else:
            return ListAllRecordsMetadata200ResponseAttachments(
        )
        """

    def testListAllRecordsMetadata200ResponseAttachments(self):
        """Test ListAllRecordsMetadata200ResponseAttachments"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
