# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.update_workflow_metadata200_response_attributes import UpdateWorkflowMetadata200ResponseAttributes

class TestUpdateWorkflowMetadata200ResponseAttributes(unittest.TestCase):
    """UpdateWorkflowMetadata200ResponseAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWorkflowMetadata200ResponseAttributes:
        """Test UpdateWorkflowMetadata200ResponseAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWorkflowMetadata200ResponseAttributes`
        """
        model = UpdateWorkflowMetadata200ResponseAttributes()
        if include_optional:
            return UpdateWorkflowMetadata200ResponseAttributes(
                counterparty_name = 'Boba Fett',
                amount = 123,
                fee = openapi_client.models.update_workflow_metadata_200_response_attributes_fee.update_workflow_metadata_200_response_attributes_fee(
                    currency = 'USD', 
                    amount = 50000, ),
                draft = [
                    openapi_client.models.update_workflow_metadata_200_response_attributes_draft_inner.update_workflow_metadata_200_response_attributes_draft_inner(
                        version = 'B1QePArXb', 
                        filename = 'file.pdf', 
                        download = '/public/api/v1/workflows/594356b9fbcd7f74006fdf8a/document/rJklwCHQ/download', )
                    ]
            )
        else:
            return UpdateWorkflowMetadata200ResponseAttributes(
        )
        """

    def testUpdateWorkflowMetadata200ResponseAttributes(self):
        """Test UpdateWorkflowMetadata200ResponseAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
