# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update_workflow_metadata200_response import UpdateWorkflowMetadata200Response

class TestUpdateWorkflowMetadata200Response(unittest.TestCase):
    """UpdateWorkflowMetadata200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWorkflowMetadata200Response:
        """Test UpdateWorkflowMetadata200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWorkflowMetadata200Response`
        """
        model = UpdateWorkflowMetadata200Response()
        if include_optional:
            return UpdateWorkflowMetadata200Response(
                id = '6013609108b8f070cee94fc1',
                ironclad_id = 'IC-1',
                title = 'Consulting Agreement with Jane Doe',
                template = '600b296c3e15a234ab88f884',
                step = 'Review',
                var_schema = openapi_client.models.update_workflow_metadata_200_response_schema.update_workflow_metadata_200_response_schema(
                    counterparty_name = openapi_client.models.update_workflow_metadata_200_response_schema_counterparty_name.update_workflow_metadata_200_response_schema_counterpartyName(
                        type = 'string', 
                        display_name = 'Example String Attribute', ), 
                    amount = openapi_client.models.update_workflow_metadata_200_response_schema_amount.update_workflow_metadata_200_response_schema_amount(
                        type = 'number', 
                        display_name = 'Example Number Attribute', ), 
                    fee = openapi_client.models.update_workflow_metadata_200_response_schema_fee.update_workflow_metadata_200_response_schema_fee(
                        type = 'monetaryAmount', 
                        display_name = 'Example Monetary Amount Attribute', ), 
                    draft = openapi_client.models.update_workflow_metadata_200_response_schema_draft.update_workflow_metadata_200_response_schema_draft(
                        type = 'array', 
                        element_type = openapi_client.models.update_workflow_metadata_200_response_schema_draft_element_type.update_workflow_metadata_200_response_schema_draft_elementType(
                            type = 'document', 
                            display_name = 'Example Document Attribute', ), ), 
                    line_items = openapi_client.models.update_workflow_metadata_200_response_schema_line_items.update_workflow_metadata_200_response_schema_lineItems(
                        type = 'array', ), ),
                attributes = openapi_client.models.update_workflow_metadata_200_response_attributes.update_workflow_metadata_200_response_attributes(
                    counterparty_name = 'Boba Fett', 
                    amount = 123, 
                    fee = openapi_client.models.update_workflow_metadata_200_response_attributes_fee.update_workflow_metadata_200_response_attributes_fee(
                        currency = 'USD', 
                        amount = 50000, ), 
                    draft = [
                        openapi_client.models.update_workflow_metadata_200_response_attributes_draft_inner.update_workflow_metadata_200_response_attributes_draft_inner(
                            version = 'B1QePArXb', 
                            filename = 'file.pdf', 
                            download = '/public/api/v1/workflows/594356b9fbcd7f74006fdf8a/document/rJklwCHQ/download', )
                        ], ),
                is_cancelled = False,
                is_complete = False,
                status = 'active',
                creator = openapi_client.models.update_workflow_metadata_200_response_creator.update_workflow_metadata_200_response_creator(
                    display_name = 'Boba Fett', 
                    email = 'fett@intergalactic.com', 
                    id = '63d415e0dd0d828c3a878548', ),
                created = '2016-11-17T00:37:22.318Z',
                last_updated = '2016-11-17T00:37:22.318Z',
                roles = [
                    openapi_client.models.list_all_workflow_approvals_200_response_roles_inner.list_all_workflow_approvals_200_response_roles_inner(
                        id = 'legal', 
                        display_name = 'Legal', 
                        assignees = [
                            openapi_client.models.list_all_workflow_approvals_200_response_roles_inner_assignees_inner.list_all_workflow_approvals_200_response_roles_inner_assignees_inner(
                                user_name = 'Boba Fett', 
                                user_id = '63d415e0dd0d828c3a878548', 
                                email = 'bobafett@gmail.com', )
                            ], )
                    ],
                approvals = openapi_client.models.update_workflow_metadata_200_response_approvals.update_workflow_metadata_200_response_approvals(
                    state = 'in_progess', 
                    url = 'https://ironcladapp.com/public/api/v1/workflows/22e2ff72-56a1-4711-a4ca-41328d311e9f/approvals', ),
                signatures = openapi_client.models.update_workflow_metadata_200_response_signatures.update_workflow_metadata_200_response_signatures(
                    state = 'in_progess', 
                    url = 'https://ironcladapp.com/public/api/v1/workflows/6dac47a10b1242d1f7df688d/signatures', ),
                record_ids = [
                    '715f1e37-292f-4e6c-8b48-c07e1b68bccd'
                    ],
                is_revertible_to_review = False
            )
        else:
            return UpdateWorkflowMetadata200Response(
        )
        """

    def testUpdateWorkflowMetadata200Response(self):
        """Test UpdateWorkflowMetadata200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
