# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.update_workflow_metadata200_response_signatures import UpdateWorkflowMetadata200ResponseSignatures

class TestUpdateWorkflowMetadata200ResponseSignatures(unittest.TestCase):
    """UpdateWorkflowMetadata200ResponseSignatures unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWorkflowMetadata200ResponseSignatures:
        """Test UpdateWorkflowMetadata200ResponseSignatures
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWorkflowMetadata200ResponseSignatures`
        """
        model = UpdateWorkflowMetadata200ResponseSignatures()
        if include_optional:
            return UpdateWorkflowMetadata200ResponseSignatures(
                state = 'in_progess',
                url = 'https://ironcladapp.com/public/api/v1/workflows/6dac47a10b1242d1f7df688d/signatures'
            )
        else:
            return UpdateWorkflowMetadata200ResponseSignatures(
        )
        """

    def testUpdateWorkflowMetadata200ResponseSignatures(self):
        """Test UpdateWorkflowMetadata200ResponseSignatures"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
