# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_all_workflow_approvals200_response import ListAllWorkflowApprovals200Response

class TestListAllWorkflowApprovals200Response(unittest.TestCase):
    """ListAllWorkflowApprovals200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllWorkflowApprovals200Response:
        """Test ListAllWorkflowApprovals200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllWorkflowApprovals200Response`
        """
        model = ListAllWorkflowApprovals200Response()
        if include_optional:
            return ListAllWorkflowApprovals200Response(
                workflow_id = '5f595f76c4fc9b3571413c3ac',
                title = 'Consulting Agreement with Michael Scott Paper Company',
                approval_groups = [
                    openapi_client.models.list_all_workflow_approvals_200_response_approval_groups_inner.list_all_workflow_approvals_200_response_approvalGroups_inner(
                        reviewers = [
                            openapi_client.models.list_all_workflow_approvals_200_response_approval_groups_inner_reviewers_inner.list_all_workflow_approvals_200_response_approvalGroups_inner_reviewers_inner(
                                role = 'finance', 
                                display_name = 'Finance', 
                                reviewer_type = 'role', 
                                status = 'pending', )
                            ], )
                    ],
                roles = [
                    openapi_client.models.list_all_workflow_approvals_200_response_roles_inner.list_all_workflow_approvals_200_response_roles_inner(
                        id = 'legal', 
                        display_name = 'Legal', 
                        assignees = [
                            openapi_client.models.list_all_workflow_approvals_200_response_roles_inner_assignees_inner.list_all_workflow_approvals_200_response_roles_inner_assignees_inner(
                                user_name = 'Boba Fett', 
                                user_id = '63d415e0dd0d828c3a878548', 
                                email = 'bobafett@gmail.com', )
                            ], )
                    ]
            )
        else:
            return ListAllWorkflowApprovals200Response(
        )
        """

    def testListAllWorkflowApprovals200Response(self):
        """Test ListAllWorkflowApprovals200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
