# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.retrieve_email_threads_from_workflow200_response import RetrieveEmailThreadsFromWorkflow200Response

class TestRetrieveEmailThreadsFromWorkflow200Response(unittest.TestCase):
    """RetrieveEmailThreadsFromWorkflow200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RetrieveEmailThreadsFromWorkflow200Response:
        """Test RetrieveEmailThreadsFromWorkflow200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RetrieveEmailThreadsFromWorkflow200Response`
        """
        model = RetrieveEmailThreadsFromWorkflow200Response()
        if include_optional:
            return RetrieveEmailThreadsFromWorkflow200Response(
                page = 0,
                page_size = 20,
                count = 1,
                list = [
                    openapi_client.models.email_response_model.EmailResponseModel()
                    ]
            )
        else:
            return RetrieveEmailThreadsFromWorkflow200Response(
        )
        """

    def testRetrieveEmailThreadsFromWorkflow200Response(self):
        """Test RetrieveEmailThreadsFromWorkflow200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
