# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.outbound_email_response import OutboundEmailResponse

class TestOutboundEmailResponse(unittest.TestCase):
    """OutboundEmailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutboundEmailResponse:
        """Test OutboundEmailResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutboundEmailResponse`
        """
        model = OutboundEmailResponse()
        if include_optional:
            return OutboundEmailResponse(
                id = '6372b491abd2adf22f6e13ff',
                type = 'outboundEmail',
                author = openapi_client.models.activity_author_model.ActivityAuthorModel(),
                timestamp = '2022-09-28T19:21:05.034Z',
                subject = 'This is the subject of an email',
                body = 'This is a body of an email.\n',
                recipients = [
                    'dopstop@ironclad.boba'
                    ],
                cc = [
                    'admiral@ironclad.boba'
                    ],
                attachments = [
                    openapi_client.models.outbound_attachment_model.OutboundAttachmentModel(
                        filename = 'attachment.pdf', 
                        content_type = 'application/pdf', 
                        download = '/public/api/v1/workflows/6013609108b8f070cee94fc1/document/XZ9j0cHGA/download', )
                    ],
                email_opened_timestamps = [
                    openapi_client.models.outbound_email_response_email_opened_timestamps_inner.OutboundEmailResponse_emailOpenedTimestamps_inner(
                        email = 'david@boba.com', 
                        opened = True, )
                    ]
            )
        else:
            return OutboundEmailResponse(
        )
        """

    def testOutboundEmailResponse(self):
        """Test OutboundEmailResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
