# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_all_workflow_signers400_response import ListAllWorkflowSigners400Response

class TestListAllWorkflowSigners400Response(unittest.TestCase):
    """ListAllWorkflowSigners400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllWorkflowSigners400Response:
        """Test ListAllWorkflowSigners400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllWorkflowSigners400Response`
        """
        model = ListAllWorkflowSigners400Response()
        if include_optional:
            return ListAllWorkflowSigners400Response(
                code = 'INVALID_STATE',
                message = 'This workflow is not at the Sign step, and is currently at the Review step'
            )
        else:
            return ListAllWorkflowSigners400Response(
        )
        """

    def testListAllWorkflowSigners400Response(self):
        """Test ListAllWorkflowSigners400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
