# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.workflow_state_model_one_of1 import WorkflowStateModelOneOf1

class TestWorkflowStateModelOneOf1(unittest.TestCase):
    """WorkflowStateModelOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowStateModelOneOf1:
        """Test WorkflowStateModelOneOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowStateModelOneOf1`
        """
        model = WorkflowStateModelOneOf1()
        if include_optional:
            return WorkflowStateModelOneOf1(
                state = 'completed'
            )
        else:
            return WorkflowStateModelOneOf1(
                state = 'completed',
        )
        """

    def testWorkflowStateModelOneOf1(self):
        """Test WorkflowStateModelOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
