# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.retrieve_import_predictions200_response_one_of_inner import RetrieveImportPredictions200ResponseOneOfInner

class TestRetrieveImportPredictions200ResponseOneOfInner(unittest.TestCase):
    """RetrieveImportPredictions200ResponseOneOfInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RetrieveImportPredictions200ResponseOneOfInner:
        """Test RetrieveImportPredictions200ResponseOneOfInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RetrieveImportPredictions200ResponseOneOfInner`
        """
        model = RetrieveImportPredictions200ResponseOneOfInner()
        if include_optional:
            return RetrieveImportPredictions200ResponseOneOfInner(
                record_id = 'df1c2805-f5a3-4a14-9386-c28d950dff49',
                status = 'ready'
            )
        else:
            return RetrieveImportPredictions200ResponseOneOfInner(
        )
        """

    def testRetrieveImportPredictions200ResponseOneOfInner(self):
        """Test RetrieveImportPredictions200ResponseOneOfInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
