# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.create_a_webhook200_response import CreateAWebhook200Response

class TestCreateAWebhook200Response(unittest.TestCase):
    """CreateAWebhook200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAWebhook200Response:
        """Test CreateAWebhook200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAWebhook200Response`
        """
        model = CreateAWebhook200Response()
        if include_optional:
            return CreateAWebhook200Response(
                id = '5928719b30182d3700364a74',
                events = [
                    'workflow_launched'
                    ],
                target_url = 'https://requestb.in/18m34b',
                company = '5928719b30182d3700364a74'
            )
        else:
            return CreateAWebhook200Response(
        )
        """

    def testCreateAWebhook200Response(self):
        """Test CreateAWebhook200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
