# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.webhook_target_url_exists_bad_request_response import WebhookTargetURLExistsBadRequestResponse

class TestWebhookTargetURLExistsBadRequestResponse(unittest.TestCase):
    """WebhookTargetURLExistsBadRequestResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookTargetURLExistsBadRequestResponse:
        """Test WebhookTargetURLExistsBadRequestResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookTargetURLExistsBadRequestResponse`
        """
        model = WebhookTargetURLExistsBadRequestResponse()
        if include_optional:
            return WebhookTargetURLExistsBadRequestResponse(
                code = 'INVALID_PARAM',
                message = 'webhook already exists for event workflow_completed and target [SOME_EXISTING_TARGET_URL]',
                param = 'tagetURL'
            )
        else:
            return WebhookTargetURLExistsBadRequestResponse(
        )
        """

    def testWebhookTargetURLExistsBadRequestResponse(self):
        """Test WebhookTargetURLExistsBadRequestResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
