# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.inbound_email_response import InboundEmailResponse

class TestInboundEmailResponse(unittest.TestCase):
    """InboundEmailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InboundEmailResponse:
        """Test InboundEmailResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InboundEmailResponse`
        """
        model = InboundEmailResponse()
        if include_optional:
            return InboundEmailResponse(
                id = '6372b491abd2adf22f6e13ff',
                email_thread_id = 'emailThread16ca903a0ec44ae09fc0b3fb3339ffa0',
                type = 'inboundEmail',
                author = openapi_client.models.activity_author_model.ActivityAuthorModel(),
                timestamp = '2022-09-28T19:21:05.034Z',
                subject = 'This is the subject of an email',
                body = 'This is a body of an email.\n',
                attachments = [
                    openapi_client.models.inbound_attachment_model.InboundAttachmentModel(
                        filename = 'file.docx', 
                        content_type = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 
                        download = '/public/api/v1/workflows/6013609108b8f070cee94fc1/emails/z_1zgjgjq/attachments/attachmentIdc85d7e3be5d84bf28cebe4591e39c894', )
                    ]
            )
        else:
            return InboundEmailResponse(
        )
        """

    def testInboundEmailResponse(self):
        """Test InboundEmailResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
