# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.workflow_state_model_one_of import WorkflowStateModelOneOf

class TestWorkflowStateModelOneOf(unittest.TestCase):
    """WorkflowStateModelOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowStateModelOneOf:
        """Test WorkflowStateModelOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowStateModelOneOf`
        """
        model = WorkflowStateModelOneOf()
        if include_optional:
            return WorkflowStateModelOneOf(
                state = 'not_started'
            )
        else:
            return WorkflowStateModelOneOf(
                state = 'not_started',
        )
        """

    def testWorkflowStateModelOneOf(self):
        """Test WorkflowStateModelOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
