# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_all_webhooks200_response_list_inner import ListAllWebhooks200ResponseListInner

class TestListAllWebhooks200ResponseListInner(unittest.TestCase):
    """ListAllWebhooks200ResponseListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllWebhooks200ResponseListInner:
        """Test ListAllWebhooks200ResponseListInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllWebhooks200ResponseListInner`
        """
        model = ListAllWebhooks200ResponseListInner()
        if include_optional:
            return ListAllWebhooks200ResponseListInner(
                id = '5928719b30182d3700364a74',
                events = [
                    'workflow_launched'
                    ],
                target_url = 'https://requestb.in/18m34bs1',
                company = '5928719b30182d3700364a74'
            )
        else:
            return ListAllWebhooks200ResponseListInner(
        )
        """

    def testListAllWebhooks200ResponseListInner(self):
        """Test ListAllWebhooks200ResponseListInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
