# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.list_all_webhooks200_response import ListAllWebhooks200Response

class TestListAllWebhooks200Response(unittest.TestCase):
    """ListAllWebhooks200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllWebhooks200Response:
        """Test ListAllWebhooks200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllWebhooks200Response`
        """
        model = ListAllWebhooks200Response()
        if include_optional:
            return ListAllWebhooks200Response(
                page = 0,
                page_size = 20,
                list = [
                    openapi_client.models.list_all_webhooks_200_response_list_inner.list_all_webhooks_200_response_list_inner(
                        id = '5928719b30182d3700364a74', 
                        events = [
                            'workflow_launched'
                            ], 
                        target_url = 'https://requestb.in/18m34bs1', 
                        company = '5928719b30182d3700364a74', )
                    ]
            )
        else:
            return ListAllWebhooks200Response(
        )
        """

    def testListAllWebhooks200Response(self):
        """Test ListAllWebhooks200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
