# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bad_request_error_record_attachment_id_not_found import BadRequestErrorRecordAttachmentIDNotFound

class TestBadRequestErrorRecordAttachmentIDNotFound(unittest.TestCase):
    """BadRequestErrorRecordAttachmentIDNotFound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BadRequestErrorRecordAttachmentIDNotFound:
        """Test BadRequestErrorRecordAttachmentIDNotFound
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BadRequestErrorRecordAttachmentIDNotFound`
        """
        model = BadRequestErrorRecordAttachmentIDNotFound()
        if include_optional:
            return BadRequestErrorRecordAttachmentIDNotFound(
                code = 'NOT_FOUND',
                message = 'couldn't find an attachment matching the key [SOME_NONEXISTENT_ATTACHMENT_KEY] for record with id [RECORD_ID]'
            )
        else:
            return BadRequestErrorRecordAttachmentIDNotFound(
        )
        """

    def testBadRequestErrorRecordAttachmentIDNotFound(self):
        """Test BadRequestErrorRecordAttachmentIDNotFound"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
