# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.record_model_properties_hourly_rate_value import RecordModelPropertiesHourlyRateValue

class TestRecordModelPropertiesHourlyRateValue(unittest.TestCase):
    """RecordModelPropertiesHourlyRateValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordModelPropertiesHourlyRateValue:
        """Test RecordModelPropertiesHourlyRateValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordModelPropertiesHourlyRateValue`
        """
        model = RecordModelPropertiesHourlyRateValue()
        if include_optional:
            return RecordModelPropertiesHourlyRateValue(
                amount = 100,
                currency = 'USD'
            )
        else:
            return RecordModelPropertiesHourlyRateValue(
        )
        """

    def testRecordModelPropertiesHourlyRateValue(self):
        """Test RecordModelPropertiesHourlyRateValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
