# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.creator_model import CreatorModel

class TestCreatorModel(unittest.TestCase):
    """CreatorModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatorModel:
        """Test CreatorModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatorModel`
        """
        model = CreatorModel()
        if include_optional:
            return CreatorModel(
                type = 'id',
                email = 'example@example.com',
                id = 'abcd1234'
            )
        else:
            return CreatorModel(
        )
        """

    def testCreatorModel(self):
        """Test CreatorModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
