# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.workflow_role_model import WorkflowRoleModel

class TestWorkflowRoleModel(unittest.TestCase):
    """WorkflowRoleModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowRoleModel:
        """Test WorkflowRoleModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowRoleModel`
        """
        model = WorkflowRoleModel()
        if include_optional:
            return WorkflowRoleModel(
                id = 'legal',
                display_name = 'Legal',
                assignees = [
                    openapi_client.models.workflow_role_assignee_model.WorkflowRoleAssigneeModel(
                        user_name = 'Boba Fett', 
                        user_id = '63d415e0dd0d828c3a878548', 
                        email = 'bobafett@gmail.com', )
                    ]
            )
        else:
            return WorkflowRoleModel(
        )
        """

    def testWorkflowRoleModel(self):
        """Test WorkflowRoleModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
