# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_a_new_workflow_async200_response import CreateANewWorkflowAsync200Response

class TestCreateANewWorkflowAsync200Response(unittest.TestCase):
    """CreateANewWorkflowAsync200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateANewWorkflowAsync200Response:
        """Test CreateANewWorkflowAsync200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateANewWorkflowAsync200Response`
        """
        model = CreateANewWorkflowAsync200Response()
        if include_optional:
            return CreateANewWorkflowAsync200Response(
                async_job_id = 'jobIda89474a8ba364f79bb510517d7bd3fea',
                async_job_status_url = 'http://ironcladapp.com/public/api/v1/workflows/async/jobIda89474a8ba364f79bb510517d7bd3fea'
            )
        else:
            return CreateANewWorkflowAsync200Response(
                async_job_id = 'jobIda89474a8ba364f79bb510517d7bd3fea',
                async_job_status_url = 'http://ironcladapp.com/public/api/v1/workflows/async/jobIda89474a8ba364f79bb510517d7bd3fea',
        )
        """

    def testCreateANewWorkflowAsync200Response(self):
        """Test CreateANewWorkflowAsync200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
