# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bad_request_error_record_attachment_unknown_content_type import BadRequestErrorRecordAttachmentUnknownContentType

class TestBadRequestErrorRecordAttachmentUnknownContentType(unittest.TestCase):
    """BadRequestErrorRecordAttachmentUnknownContentType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BadRequestErrorRecordAttachmentUnknownContentType:
        """Test BadRequestErrorRecordAttachmentUnknownContentType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BadRequestErrorRecordAttachmentUnknownContentType`
        """
        model = BadRequestErrorRecordAttachmentUnknownContentType()
        if include_optional:
            return BadRequestErrorRecordAttachmentUnknownContentType(
                code = 'INVALID_PARAM',
                message = 'unknown content type 'filename or extension'',
                param = 'metadata.filename'
            )
        else:
            return BadRequestErrorRecordAttachmentUnknownContentType(
        )
        """

    def testBadRequestErrorRecordAttachmentUnknownContentType(self):
        """Test BadRequestErrorRecordAttachmentUnknownContentType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
