# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.list_all_workflow_participants404_response import ListAllWorkflowParticipants404Response

class TestListAllWorkflowParticipants404Response(unittest.TestCase):
    """ListAllWorkflowParticipants404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllWorkflowParticipants404Response:
        """Test ListAllWorkflowParticipants404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllWorkflowParticipants404Response`
        """
        model = ListAllWorkflowParticipants404Response()
        if include_optional:
            return ListAllWorkflowParticipants404Response(
                code = 'NOT_FOUND',
                message = 'workflow does not exist',
                param = 'workflowId'
            )
        else:
            return ListAllWorkflowParticipants404Response(
        )
        """

    def testListAllWorkflowParticipants404Response(self):
        """Test ListAllWorkflowParticipants404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
