# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.approval_requests403_response import ApprovalRequests403Response

class TestApprovalRequests403Response(unittest.TestCase):
    """ApprovalRequests403Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApprovalRequests403Response:
        """Test ApprovalRequests403Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApprovalRequests403Response`
        """
        model = ApprovalRequests403Response()
        if include_optional:
            return ApprovalRequests403Response(
                code = 'FORBIDDEN',
                message = 'access forbidden'
            )
        else:
            return ApprovalRequests403Response(
        )
        """

    def testApprovalRequests403Response(self):
        """Test ApprovalRequests403Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
