# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.retrieve_email_thread_from_workflow404_response import RetrieveEmailThreadFromWorkflow404Response

class TestRetrieveEmailThreadFromWorkflow404Response(unittest.TestCase):
    """RetrieveEmailThreadFromWorkflow404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RetrieveEmailThreadFromWorkflow404Response:
        """Test RetrieveEmailThreadFromWorkflow404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RetrieveEmailThreadFromWorkflow404Response`
        """
        model = RetrieveEmailThreadFromWorkflow404Response()
        if include_optional:
            return RetrieveEmailThreadFromWorkflow404Response(
                code = 'NOT_FOUND',
                message = 'emailThreadId does not exist',
                param = 'emailThreadId'
            )
        else:
            return RetrieveEmailThreadFromWorkflow404Response(
        )
        """

    def testRetrieveEmailThreadFromWorkflow404Response(self):
        """Test RetrieveEmailThreadFromWorkflow404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
