# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.bad_request_error_record_attachment_unknown_attachment_key import BadRequestErrorRecordAttachmentUnknownAttachmentKey

class TestBadRequestErrorRecordAttachmentUnknownAttachmentKey(unittest.TestCase):
    """BadRequestErrorRecordAttachmentUnknownAttachmentKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BadRequestErrorRecordAttachmentUnknownAttachmentKey:
        """Test BadRequestErrorRecordAttachmentUnknownAttachmentKey
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BadRequestErrorRecordAttachmentUnknownAttachmentKey`
        """
        model = BadRequestErrorRecordAttachmentUnknownAttachmentKey()
        if include_optional:
            return BadRequestErrorRecordAttachmentUnknownAttachmentKey(
                code = 'INVALID_PARAM',
                message = 'unknown record attachment key 'someRandomKey'',
                param = 'attachmentKey'
            )
        else:
            return BadRequestErrorRecordAttachmentUnknownAttachmentKey(
        )
        """

    def testBadRequestErrorRecordAttachmentUnknownAttachmentKey(self):
        """Test BadRequestErrorRecordAttachmentUnknownAttachmentKey"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
