# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ironclad_python.models.list_all_workflow_signers200_response import ListAllWorkflowSigners200Response

class TestListAllWorkflowSigners200Response(unittest.TestCase):
    """ListAllWorkflowSigners200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllWorkflowSigners200Response:
        """Test ListAllWorkflowSigners200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllWorkflowSigners200Response`
        """
        model = ListAllWorkflowSigners200Response()
        if include_optional:
            return ListAllWorkflowSigners200Response(
                workflow_id = '6dac47a10b1242d1f7df688d',
                title = 'Goldendoodle Adoption Contract',
                signers = [
                    openapi_client.models.list_all_workflow_signers_200_response_signers_inner.list_all_workflow_signers_200_response_signers_inner(
                        name = 'Jimothy Kim', 
                        email = 'jimothykim@gmail.com', 
                        role_name = 'Counterparty Signer', 
                        signature_status = 'sent', 
                        delegates = [
                            openapi_client.models.list_all_workflow_signers_200_response_signers_inner_delegates_inner.list_all_workflow_signers_200_response_signers_inner_delegates_inner(
                                name = 'Kim Lam', 
                                email = 'kimlam@gmail.com', )
                            ], )
                    ]
            )
        else:
            return ListAllWorkflowSigners200Response(
        )
        """

    def testListAllWorkflowSigners200Response(self):
        """Test ListAllWorkflowSigners200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
