# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.record_model import RecordModel

class TestRecordModel(unittest.TestCase):
    """RecordModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordModel:
        """Test RecordModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordModel`
        """
        model = RecordModel()
        if include_optional:
            return RecordModel(
                id = '22e2ff72-56a1-4711-a4ca-41328d311e9f',
                ironclad_id = 'IC-1',
                type = 'consultingAgreement',
                name = 'Consulting Agreement with Jane Doe',
                last_updated = '2018-05-08T17:28:10Z',
                properties = openapi_client.models.record_model_properties.RecordModel_properties(
                    agreement_date = openapi_client.models.record_model_properties_agreement_date.RecordModel_properties_agreementDate(
                        type = 'date', 
                        value = '2018-05-08T00:00:00-07:00', ), 
                    counterparty_name = openapi_client.models.record_model_properties_counterparty_name.RecordModel_properties_counterpartyName(
                        type = 'string', 
                        value = 'Jane Doe', ), 
                    counterparty_email = openapi_client.models.record_model_properties_counterparty_email.RecordModel_properties_counterpartyEmail(
                        type = 'email', 
                        value = 'jane.doe@test.com', ), 
                    hourly_rate = openapi_client.models.record_model_properties_hourly_rate.RecordModel_properties_hourlyRate(
                        type = 'monetaryAmount', 
                        value = openapi_client.models.record_model_properties_hourly_rate_value.RecordModel_properties_hourlyRate_value(
                            amount = 100, 
                            currency = 'USD', ), ), ),
                attachments = openapi_client.models.record_model_attachments.RecordModel_attachments(
                    signed_copy = openapi_client.models.record_model_attachments_signed_copy.RecordModel_attachments_signedCopy(
                        filename = '2018-05-08 - Doe, Jane - Consulting Agreement.pdf', 
                        content_type = 'application/json', 
                        href = 'https://ironcladapp.com/public/api/v1/records/22e2ff72-56a1-4711-a4ca-41328d311e9f/attachments/signedCopy', ), ),
                links = [
                    openapi_client.models.record_model_links_inner.RecordModel_links_inner(
                        record_id = 'df1c2805-f5a3-4a14-9386-c28d950dff49', )
                    ],
                parent_id = 'd10b8c01-5c54-4a59-82cb-51e3825182e9',
                child_ids = [
                    '4a785686-d3d5-47bc-960e-3df0df871ea9'
                    ],
                source = openapi_client.models.record_model_source.RecordModel_source(
                    type = 'workflow', 
                    workflow_id = 'abcd1234', )
            )
        else:
            return RecordModel(
        )
        """

    def testRecordModel(self):
        """Test RecordModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
