# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update_workflow_metadata200_response_attributes_fee import UpdateWorkflowMetadata200ResponseAttributesFee

class TestUpdateWorkflowMetadata200ResponseAttributesFee(unittest.TestCase):
    """UpdateWorkflowMetadata200ResponseAttributesFee unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWorkflowMetadata200ResponseAttributesFee:
        """Test UpdateWorkflowMetadata200ResponseAttributesFee
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWorkflowMetadata200ResponseAttributesFee`
        """
        model = UpdateWorkflowMetadata200ResponseAttributesFee()
        if include_optional:
            return UpdateWorkflowMetadata200ResponseAttributesFee(
                currency = 'USD',
                amount = 50000
            )
        else:
            return UpdateWorkflowMetadata200ResponseAttributesFee(
        )
        """

    def testUpdateWorkflowMetadata200ResponseAttributesFee(self):
        """Test UpdateWorkflowMetadata200ResponseAttributesFee"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
