# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.inbound_attachment_model import InboundAttachmentModel

class TestInboundAttachmentModel(unittest.TestCase):
    """InboundAttachmentModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InboundAttachmentModel:
        """Test InboundAttachmentModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InboundAttachmentModel`
        """
        model = InboundAttachmentModel()
        if include_optional:
            return InboundAttachmentModel(
                filename = 'file.docx',
                content_type = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                download = '/public/api/v1/workflows/6013609108b8f070cee94fc1/emails/z_1zgjgjq/attachments/attachmentIdc85d7e3be5d84bf28cebe4591e39c894'
            )
        else:
            return InboundAttachmentModel(
        )
        """

    def testInboundAttachmentModel(self):
        """Test InboundAttachmentModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
