# coding: utf-8

"""
    Ironclad Public API

    Documentation for Ironclad's REST API.

    The version of the OpenAPI document: 1
    Contact: support@ironcladapp.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.update_workflow_metadata200_response_attributes_fee import UpdateWorkflowMetadata200ResponseAttributesFee
from openapi_client.models.workflow_response_model_attributes_draft_inner import WorkflowResponseModelAttributesDraftInner
from typing import Optional, Set
from typing_extensions import Self

class WorkflowResponseModelAttributes(BaseModel):
    """
    WorkflowResponseModelAttributes
    """ # noqa: E501
    counterparty_name: Optional[StrictStr] = Field(default=None, alias="counterpartyName")
    amount: Optional[StrictInt] = 0
    fee: Optional[UpdateWorkflowMetadata200ResponseAttributesFee] = None
    draft: Optional[List[WorkflowResponseModelAttributesDraftInner]] = None
    __properties: ClassVar[List[str]] = ["counterpartyName", "amount", "fee", "draft"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowResponseModelAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of fee
        if self.fee:
            _dict['fee'] = self.fee.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in draft (list)
        _items = []
        if self.draft:
            for _item_draft in self.draft:
                if _item_draft:
                    _items.append(_item_draft.to_dict())
            _dict['draft'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowResponseModelAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "counterpartyName": obj.get("counterpartyName"),
            "amount": obj.get("amount") if obj.get("amount") is not None else 0,
            "fee": UpdateWorkflowMetadata200ResponseAttributesFee.from_dict(obj["fee"]) if obj.get("fee") is not None else None,
            "draft": [WorkflowResponseModelAttributesDraftInner.from_dict(_item) for _item in obj["draft"]] if obj.get("draft") is not None else None
        })
        return _obj


